In [31]:
import numpy as np
import pandas as pd

## load and see the dataset

In [26]:
dataset = pd.read_csv("NFL Play by Play 2009-2016 (v3).csv")

/tmp/ipykernel_83214/2305188295.py:1: DtypeWarning: Columns (0: DefTwoPoint, 1: BlockingPlayer) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv("NFL Play by Play 2009-2016 (v3).csv")

In [ ]:
'''
    - dekho upore dataset load korar shomoy ekta warning dise. warning ta holo DtypeWarning. warning ta bolche je, ekta column er moddhe mixed data type ache.
    
    - eta duivabe solve kora jay
'''

In [27]:
# প্রথম ৫টি row দেখি
# NaN / None আছে কিনা observe করি
dataset.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

## investigate the dataset

In [30]:
# Count Missing Values

missing_values_count = dataset.isnull().sum()

# missing_values_count[:10]
missing_values_count

Date             0
GameID           0
Drive            0
qtr              0
down         54218
             ...
Win_Prob     21993
WPA           4817
airWPA      220738
yacWPA      220956
Season           0
Length: 102, dtype: int64

In [ ]:
# Missing Percentage

# amake dekhte hobe full dataset er koto percent value missing.

total_cells = np.prod(dataset.shape)

total_missing = missing_values_count.sum()

percent_missing = (total_missing / total_cells) * 100

print(percent_missing)

27.652267428200588

## Data Intuition

In [10]:
# ============================================================
# Step 6: Data Intuition
# ============================================================

'''
প্রশ্ন:
Missing value কেন?

১. Wasn't Recorded
- Data থাকার কথা ছিল।
- Record করা হয়নি।
- Example:
  User Age
  Student CGPA

=> সাধারণত Fill / Impute করা যায়।

২. Doesn't Exist
- Data বাস্তবেই নেই।
- Example:
  Spouse Name (Unmarried Student)

=> সাধারণত NaN রেখে দেওয়া ভালো।
'''

pass

In [11]:
# ============================================================
# Step 7: Drop Missing Rows
# ============================================================

# যেসব row-এ অন্তত একটি NaN আছে সেগুলো delete হবে
nfl_data.dropna()

Empty DataFrame
Columns: [Date, GameID, Drive, qtr, down, time, TimeUnder, TimeSecs, PlayTimeDiff, SideofField, yrdln, yrdline100, ydstogo, ydsnet, GoalToGo, FirstDown, posteam, DefensiveTeam, desc, PlayAttempted, Yards.Gained, sp, Touchdown, ExPointResult, TwoPointConv, DefTwoPoint, Safety, Onsidekick, PuntResult, PlayType, Passer, Passer_ID, PassAttempt, PassOutcome, PassLength, AirYards, YardsAfterCatch, QBHit, PassLocation, InterceptionThrown, Interceptor, Rusher, Rusher_ID, RushAttempt, RunLocation, RunGap, Receiver, Receiver_ID, Reception, ReturnResult, Returner, BlockingPlayer, Tackler1, Tackler2, FieldGoalResult, FieldGoalDistance, Fumble, RecFumbTeam, RecFumbPlayer, Sack, Challenge.Replay, ChalReplayResult, Accepted.Penalty, PenalizedTeam, PenaltyType, PenalizedPlayer, Penalty.Yards, PosTeamScore, DefTeamScore, ScoreDiff, AbsScoreDiff, HomeTeam, AwayTeam, Timeout_Indicator, Timeout_Team, posteam_timeouts_pre, HomeTimeouts_Remaining_Pre, AwayTimeouts_Remaining_Pre, HomeTimeouts_Remaining_Post, AwayTimeouts_Remaining_Post, No_Score_Prob, Opp_Field_Goal_Prob, Opp_Safety_Prob, Opp_Touchdown_Prob, Field_Goal_Prob, Safety_Prob, Touchdown_Prob, ExPoint_Prob, TwoPoint_Prob, ExpPts, EPA, airEPA, yacEPA, Home_WP_pre, Away_WP_pre, Home_WP_post, Away_WP_post, Win_Prob, WPA, airWPA, ...]
Index: []

[0 rows x 102 columns]

In [12]:
# ============================================================
# Step 8: Drop Missing Columns
# ============================================================

columns_with_na_dropped = nfl_data.dropna(axis=1)

columns_with_na_dropped.head()

,Date,GameID,Drive,qtr,TimeUnder,ydstogo,ydsnet,PlayAttempted,Yards.Gained,sp,...,AwayTeam,Timeout_Indicator,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,ExPoint_Prob,TwoPoint_Prob,Season
0,2009-09-10,2009091000,1,1,15,0,0,1,39,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
1,2009-09-10,2009091000,1,1,15,10,5,1,5,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
2,2009-09-10,2009091000,1,1,15,5,2,1,-3,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
3,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009
4,2009-09-10,2009091000,1,1,14,8,2,1,0,0,...,TEN,0,3,3,3,3,3,0.0,0.0,2009

In [13]:
# ============================================================
# Step 9: Compare Columns
# ============================================================

print("Original Columns :", nfl_data.shape[1])
print("Remaining Columns:", columns_with_na_dropped.shape[1])

Original Columns : 102
Remaining Columns: 37

In [14]:
# ============================================================
# Step 10: Create Small Subset
# ============================================================

subset_nfl_data = nfl_data.loc[:, "EPA":"Season"].head()

subset_nfl_data

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,NaN,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,NaN,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,NaN,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

## handle the missing values

In [15]:
# ============================================================
# Step 11: Fill Missing Values
# ============================================================

# সব NaN এর জায়গায় 0 বসাবে
subset_nfl_data.fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,0.000000,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,0.000000,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

In [17]:
# ============================================================
# Step 12: Back Fill
# ============================================================

'''
bfill = নিচের valid value দিয়ে NaN পূরণ করে।

Example

10
NaN
30

↓

10
30
30
'''

#subset_nfl_data.fillna(method="bfill", axis=0)
subset_nfl_data.bfill(axis=0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,-1.068169,1.146076,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,3.318841,-5.031425,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,NaN,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [19]:
# ============================================================
# Step 13: Back Fill + fillna
# ============================================================

'''
যদি সবচেয়ে নিচের row-ও NaN হয়,
তাহলে bfill সেটা পূরণ করতে পারবে না।

তাই শেষে fillna(0) ব্যবহার করা হয়।
'''

# subset_nfl_data.fillna(method="bfill", axis=0).fillna(0)
subset_nfl_data.bfill(axis=0).fillna(0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,-1.068169,1.146076,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,-0.032244,0.036899,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,3.318841,-5.031425,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.106663,-0.156239,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,0.000000,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009

In [21]:
# ============================================================
# Step 14: Forward Fill (Extra)
# ============================================================

'''
ffill = উপরের valid value দিয়ে NaN পূরণ করে।
'''

# subset_nfl_data.fillna(method="ffill", axis=0)

subset_nfl_data.ffill(axis=0)

,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2.014474,NaN,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,0.077907,-1.068169,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,-1.402760,-1.068169,1.146076,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,-0.032244,0.036899,2009
3,-1.712583,3.318841,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2.097796,3.318841,-5.031425,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.106663,-0.156239,2009

In [22]:
# ============================================================
# Quick Revision
# ============================================================

'''
head()
    প্রথম ৫টি row

isnull()
    Missing value detect

sum()
    Missing value count

shape
    (rows, columns)

dropna()
    Missing row remove

dropna(axis=1)
    Missing column remove

fillna(0)
    নির্দিষ্ট value দিয়ে fill

fillna(method="bfill")
    নিচের value দিয়ে fill

fillna(method="ffill")
    উপরের value দিয়ে fill

Rule

Wasn't Recorded
    Fill / Impute

Doesn't Exist
    NaN রাখা যায়
'''

pass