In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.random.rand(6,5)
data

array([[0.99276525, 0.32001038, 0.75435978, 0.73881088, 0.26266195],
       [0.53648171, 0.78911447, 0.50302502, 0.28527274, 0.32234888],
       [0.15208884, 0.63843144, 0.68422998, 0.03552326, 0.94792035],
       [0.35782266, 0.83665026, 0.43434854, 0.47976294, 0.38411165],
       [0.13121052, 0.38327504, 0.02465622, 0.23729686, 0.43038461],
       [0.61092128, 0.90008831, 0.55053725, 0.20273931, 0.34608034]])

In [46]:
df = pd.DataFrame(data=data)
df

          0         1         2         3         4
0  0.456528 -0.138300  0.733793  1.134584 -0.579893
1  0.054466 -0.963711  0.991653  0.770526 -2.459180
2 -1.928267  0.684807  0.815529 -2.336034  0.555585
3 -0.756921  0.208659 -1.089598  0.923446  0.803863
4  0.548297  1.212375 -0.702221  1.040336 -1.882291
5 -0.526131  0.373286 -0.638212 -0.973034 -0.881785
6 -0.317867 -0.061939 -0.765947  0.117703 -0.818730
7  0.160439 -0.134880  0.403132  1.191251  1.646582

# Dataframe selection(indexing) - 1

In [4]:
# dataframe hocche onekgula data series er column collection. mane onekgula data seriese ke column hishebe store korle sheta dataframe hoye jabe.

df[0] # etar maddhome first column(not first row) access pabo. data series e index(row er) and value thake only.

0    0.992765
1    0.536482
2    0.152089
3    0.357823
4    0.131211
5    0.610921
Name: 0, dtype: float64

In [5]:
# dataframe er protita column je ekta series tar prove:

type(df[0])

pandas.Series

In [6]:
df2 = pd.DataFrame(
    data = data,
    index = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.992765  0.320010  0.754360  0.738811  0.262662
row2  0.536482  0.789114  0.503025  0.285273  0.322349
row3  0.152089  0.638431  0.684230  0.035523  0.947920
row4  0.357823  0.836650  0.434349  0.479763  0.384112
row5  0.131211  0.383275  0.024656  0.237297  0.430385
row6  0.610921  0.900088  0.550537  0.202739  0.346080

In [7]:
df2['col1']

row1    0.992765
row2    0.536482
row3    0.152089
row4    0.357823
row5    0.131211
row6    0.610921
Name: col1, dtype: float64

In [8]:
# see multiple columns

df2[['col1', 'col2', 'col3']]

          col1      col2      col3
row1  0.992765  0.320010  0.754360
row2  0.536482  0.789114  0.503025
row3  0.152089  0.638431  0.684230
row4  0.357823  0.836650  0.434349
row5  0.131211  0.383275  0.024656
row6  0.610921  0.900088  0.550537

## add new column in datafram

In [9]:
# important: new column add korte element shongkha hote hobe row er shoman.

df2['new_col1'] = [1, 2, 3, 4, 5, 6]
df2['new_col2'] = np.random.rand(6)

df2

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.992765  0.320010  0.754360  0.738811  0.262662         1  0.213342
row2  0.536482  0.789114  0.503025  0.285273  0.322349         2  0.711759
row3  0.152089  0.638431  0.684230  0.035523  0.947920         3  0.736045
row4  0.357823  0.836650  0.434349  0.479763  0.384112         4  0.242288
row5  0.131211  0.383275  0.024656  0.237297  0.430385         5  0.402745
row6  0.610921  0.900088  0.550537  0.202739  0.346080         6  0.693463

# remove row and column from dataframe

In [10]:
# dy default drop method row ke delete kore. but eta main datafram ke modify kore na. new ekta dataframe return kore.
df2.drop('row3')

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.992765  0.320010  0.754360  0.738811  0.262662         1  0.213342
row2  0.536482  0.789114  0.503025  0.285273  0.322349         2  0.711759
row4  0.357823  0.836650  0.434349  0.479763  0.384112         4  0.242288
row5  0.131211  0.383275  0.024656  0.237297  0.430385         5  0.402745
row6  0.610921  0.900088  0.550537  0.202739  0.346080         6  0.693463

In [11]:
# column remove using drop method:

df2.drop(columns= 'new_col2')

          col1      col2      col3      col4      col5  new_col1
row1  0.992765  0.320010  0.754360  0.738811  0.262662         1
row2  0.536482  0.789114  0.503025  0.285273  0.322349         2
row3  0.152089  0.638431  0.684230  0.035523  0.947920         3
row4  0.357823  0.836650  0.434349  0.479763  0.384112         4
row5  0.131211  0.383275  0.024656  0.237297  0.430385         5
row6  0.610921  0.900088  0.550537  0.202739  0.346080         6

In [12]:
# upore drop method use kore row3 and new_col2 remove kora hoise. but main dataframe aager motoi ase. karon drop method main dataframe ke modify kore na. 

df2

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.992765  0.320010  0.754360  0.738811  0.262662         1  0.213342
row2  0.536482  0.789114  0.503025  0.285273  0.322349         2  0.711759
row3  0.152089  0.638431  0.684230  0.035523  0.947920         3  0.736045
row4  0.357823  0.836650  0.434349  0.479763  0.384112         4  0.242288
row5  0.131211  0.383275  0.024656  0.237297  0.430385         5  0.402745
row6  0.610921  0.900088  0.550537  0.202739  0.346080         6  0.693463

In [13]:
# main dataframe ke modify korte hole drop method er sathe inplace=True use korte hobe. 

df2.drop(columns= 'new_col2', inplace=True)
df2

          col1      col2      col3      col4      col5  new_col1
row1  0.992765  0.320010  0.754360  0.738811  0.262662         1
row2  0.536482  0.789114  0.503025  0.285273  0.322349         2
row3  0.152089  0.638431  0.684230  0.035523  0.947920         3
row4  0.357823  0.836650  0.434349  0.479763  0.384112         4
row5  0.131211  0.383275  0.024656  0.237297  0.430385         5
row6  0.610921  0.900088  0.550537  0.202739  0.346080         6

## remove row and column from dataframe using axis

In [14]:
df2

          col1      col2      col3      col4      col5  new_col1
row1  0.992765  0.320010  0.754360  0.738811  0.262662         1
row2  0.536482  0.789114  0.503025  0.285273  0.322349         2
row3  0.152089  0.638431  0.684230  0.035523  0.947920         3
row4  0.357823  0.836650  0.434349  0.479763  0.384112         4
row5  0.131211  0.383275  0.024656  0.237297  0.430385         5
row6  0.610921  0.900088  0.550537  0.202739  0.346080         6

In [15]:
# first e dataframe er shape(dimention) jante hobe.
df2.shape

(6, 6)

In [16]:
# dataframe er shape pailam (6,6). eta ekta tuple. so etaro index ase. first index row ke indicate kore and second index column ke indicate kore. 

# row delete:
df2.drop('row2', inplace = False, axis = 0) # row delete korbo tai axis = 0 dite hobe

          col1      col2      col3      col4      col5  new_col1
row1  0.992765  0.320010  0.754360  0.738811  0.262662         1
row3  0.152089  0.638431  0.684230  0.035523  0.947920         3
row4  0.357823  0.836650  0.434349  0.479763  0.384112         4
row5  0.131211  0.383275  0.024656  0.237297  0.430385         5
row6  0.610921  0.900088  0.550537  0.202739  0.346080         6

In [17]:
# column delete:
df2.drop('new_col1', inplace = False, axis = 1) # column delete korbo tai axis = 1 dite hobe

          col1      col2      col3      col4      col5
row1  0.992765  0.320010  0.754360  0.738811  0.262662
row2  0.536482  0.789114  0.503025  0.285273  0.322349
row3  0.152089  0.638431  0.684230  0.035523  0.947920
row4  0.357823  0.836650  0.434349  0.479763  0.384112
row5  0.131211  0.383275  0.024656  0.237297  0.430385
row6  0.610921  0.900088  0.550537  0.202739  0.346080

# Dataframe selection using loc and iloc

In [18]:
df3 = pd.DataFrame(
    data = np.random.randint(1, 100, size=(6, 5)),
    index = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5']
)

df3

      col1  col2  col3  col4  col5
row1    79    52    10    98    34
row2    72    40    66     3    66
row3    26     3    40    42    10
row4     4    60    17     6    36
row5    14    33    70    53    65
row6    92    41    80     7    89

## loc attribute

In [19]:
# loc means location
# loc syntax: df.loc[row_label, column_label]

# row select
df3.loc['row2'] # etaw ekta dataframe series return korbe.

col1    72
col2    40
col3    66
col4     3
col5    66
Name: row2, dtype: int64

In [50]:
# multiple row select
df3.loc[['row2', 'row3']]

      col1  col2  col3  col4  col5
row2    72    40    66     3    66
row3    26     3    40    42    10

In [20]:
# column select using loc method.
df3.loc[:, 'col2'] 

# df3['col2']  ---> eta o same kaj korbe. but loc method use korle row aage select kore then column select korte hobe. real project e only column select korte hole evabei select kora hoy. but slicing or row lagle tokhon .loc method use kora hoy.

row1    52
row2    40
row3     3
row4    60
row5    33
row6    41
Name: col2, dtype: int64

In [21]:
# multiple column select 
df3[['col2', 'col3']] 

# loc mthod: df3.loc[:, ['col2', 'col3']]

      col2  col3
row1    52    10
row2    40    66
row3     3    40
row4    60    17
row5    33    70
row6    41    80

In [22]:
# select specific value using loc method.
df3.loc['row2', 'col2']

np.int64(40)

In [23]:
df3

      col1  col2  col3  col4  col5
row1    79    52    10    98    34
row2    72    40    66     3    66
row3    26     3    40    42    10
row4     4    60    17     6    36
row5    14    33    70    53    65
row6    92    41    80     7    89

In [51]:
# ekhon ami 55,50, 97, 82 dekhte chai. mane row2 and row3 er col2 and col3 dekhte chai.

# df3.loc[['row2', 'row3']] --> eta row2 and row3 er sob column return korbe. but ami sudhu col2 and col3 dekhte chai. so ami column o select korte hobe.

df3.loc[['row2', 'row3'], ['col2', 'col3']]

      col2  col3
row2    40    66
row3     3    40

In [52]:
# row slice

df3.loc['row2':'row5']

      col1  col2  col3  col4  col5
row2    72    40    66     3    66
row3    26     3    40    42    10
row4     4    60    17     6    36
row5    14    33    70    53    65

In [53]:
# column slice
df3.loc[:, 'col2':'col4']

      col2  col3  col4
row1    52    10    98
row2    40    66     3
row3     3    40    42
row4    60    17     6
row5    33    70    53
row6    41    80     7

In [54]:
# row slice + column slice
df3.loc[
    'row2':'row5',
    'col2':'col4'
]

      col2  col3  col4
row2    40    66     3
row3     3    40    42
row4    60    17     6
row5    33    70    53

In [55]:
# row slice + single column select
df3.loc['row1':'row5', 'col1']

row1    79
row2    72
row3    26
row4     4
row5    14
Name: col1, dtype: int64

## iloc attribute

In [48]:
# iloc means integer location.

df3

      col1  col2  col3  col4  col5
row1    79    52    10    98    34
row2    72    40    66     3    66
row3    26     3    40    42    10
row4     4    60    17     6    36
row5    14    33    70    53    65
row6    92    41    80     7    89

In [27]:
# iloc diye jokhon selection korbo tokhon row and column ke integer value diye select korte hobe. also output ew row and column er nam integer value te show korbe.

# single element select:
df3.iloc[1, 1] # row2 and col2 er value show kor

np.int64(40)

In [28]:
# multiple row and column select:

df3.iloc[[1,2]]

      col1  col2  col3  col4  col5
row2    72    40    66     3    66
row3    26     3    40    42    10

In [29]:
df3.iloc[[1,2], [1,2]]

      col2  col3
row2    40    66
row3     3    40

### Choosing between loc and iloc (একটি গুরুত্বপূর্ণ পার্থক্য!)

`loc` এবং `iloc` এর মধ্যে কাজ করতে গেলে একটি বড় "gotcha" বা ফাঁদ আছে, যা মাথায় রাখা খুব জরুরি। এই দুটি মেথড ইনডেক্সিং করার সময় একটু ভিন্ন নিয়ম মেনে চলে।

* **`iloc`:** এটি Python-এর স্ট্যান্ডার্ড ইনডেক্সিং নিয়ম মেনে চলে। অর্থাৎ, রেঞ্জ দিলে প্রথমটি ইনক্লুড হয়, কিন্তু শেষেরটি এক্সক্লুড (বাদ) হয়ে যায়। তাই `0:10` দিলে এটি 0 থেকে 9 পর্যন্ত (মোট ১০টি) ভ্যালু সিলেক্ট করবে।
* **`loc`:** এটি **inclusively** (সবগুলো ধরে) ইনডেক্স করে। তাই `0:10` দিলে এটি 0 থেকে 10 পর্যন্ত (মোট ১১টি) ভ্যালু সিলেক্ট করবে!

**কেন এই পরিবর্তন?**
কারণ `loc` দিয়ে string বা টেক্সট ইনডেক্সও রেঞ্জ করা যায়। ধরুন, আপনার ইনডেক্সে 'Apples' থেকে 'Potatoes' পর্যন্ত অনেকগুলো নাম আছে। আপনি যদি `df.loc['Apples':'Potatoes']` লেখেন, তবে আপনি চাইবেন 'Potatoes' নামটিও লিস্টে থাকুক। যদি `iloc`-এর মতো কাজ করতো, তবে আপনাকে 'Potatoes'-এর পরের শব্দটি (যেমন 'Potatoet') খুঁজে বের করে লিখতে হতো, যা খুবই ঝামেলার।

এই নিয়মটি তখন খুব কনফিউজিং হয়ে যায়, যখন আপনার ইনডেক্সগুলো `0, 1, 2... 1000` নাম্বারে থাকে। `df.iloc[0:1000]` আপনাকে ঠিক 1000টি ডেটাই দেবে, কিন্তু `df.loc[0:1000]` আপনাকে 1001টি ডেটা দেবে! তাই `loc` দিয়ে ঠিক 1000টি ডেটা পেতে চাইলে আপনাকে এক ঘর কমিয়ে `df.loc[0:999]` লিখতে হবে।

# Conditional Selection

In [30]:
data= np.random.randn(8, 5)

df = pd.DataFrame(
    data=data,
    index=['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df

          col1      col2      col3      col4      col5
row1  0.456528 -0.138300  0.733793  1.134584 -0.579893
row2  0.054466 -0.963711  0.991653  0.770526 -2.459180
row3 -1.928267  0.684807  0.815529 -2.336034  0.555585
row4 -0.756921  0.208659 -1.089598  0.923446  0.803863
row5  0.548297  1.212375 -0.702221  1.040336 -1.882291
row6 -0.526131  0.373286 -0.638212 -0.973034 -0.881785
row7 -0.317867 -0.061939 -0.765947  0.117703 -0.818730
row8  0.160439 -0.134880  0.403132  1.191251  1.646582

In [31]:
# jei value gula 0 er theke boro tader dekhte chai

df[df>0]

          col1      col2      col3      col4      col5
row1  0.456528       NaN  0.733793  1.134584       NaN
row2  0.054466       NaN  0.991653  0.770526       NaN
row3       NaN  0.684807  0.815529       NaN  0.555585
row4       NaN  0.208659       NaN  0.923446  0.803863
row5  0.548297  1.212375       NaN  1.040336       NaN
row6       NaN  0.373286       NaN       NaN       NaN
row7       NaN       NaN       NaN  0.117703       NaN
row8  0.160439       NaN  0.403132  1.191251  1.646582

In [32]:
# column 3 er jei value gula 0 er theke boro tader dekhte chai
df[df['col3']>0]

          col1      col2      col3      col4      col5
row1  0.456528 -0.138300  0.733793  1.134584 -0.579893
row2  0.054466 -0.963711  0.991653  0.770526 -2.459180
row3 -1.928267  0.684807  0.815529 -2.336034  0.555585
row8  0.160439 -0.134880  0.403132  1.191251  1.646582

In [33]:
# multiple conditional selection:

# pandas e multi conditional selection e ektu careful thakte hobe. python or cpp te amra contion apply kori logical and, logical or diye. but pandas e kintu bitwise and(&), bitwise or(|) use korte hobe.

# like ami column 3 and column 5 both column er jei value gula positive shudhu tader dekhabe.

df[(df['col3']>0) & (df['col5']>0)] # biwsie operator use korte must be bracket dite hobe condition e.

          col1      col2      col3      col4      col5
row3 -1.928267  0.684807  0.815529 -2.336034  0.555585
row8  0.160439 -0.134880  0.403132  1.191251  1.646582

In [34]:
# ami uporer code e  bitwise and(&) and use korsi. ami jodi logical and use kortam tahole error show korto.

df[(df['col3']>0) and (df['col5']>0)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# uporer error er reason holo logical and, logical or just boolean value niye kaj kore. but ekhane amra duita column er upor condition apply korsi. and ei column gula holo ekta series.

# so ekhane compare hocche: pandas series vs pandas series. tai amader bitwise operators use korte hobe.

type(df['col3']>0)

pandas.Series

## three methods of conditional selection: isin(), isnull(), notnull()

In [35]:
df = pd.DataFrame({
    'Name': ['Rahim', 'Karim', 'Jihad', 'Sakib', 'Nabil', 'Rafi'],
    'Country': ['Bangladesh', 'India', 'Japan', 'Bangladesh', 'USA', np.nan],
    'Salary': [30000, np.nan, 45000, 50000, np.nan, 40000]
})

df

    Name     Country   Salary
0  Rahim  Bangladesh  30000.0
1  Karim       India      NaN
2  Jihad       Japan  45000.0
3  Sakib  Bangladesh  50000.0
4  Nabil         USA      NaN
5   Rafi         NaN  40000.0

### isin() method

In [36]:
# isin() এর অর্থ: "এই value কি এই list-এর মধ্যে আছে?"


# only bangladesh er student dekhte chai
df.loc[df['Country'] == 'Bangladesh']

    Name     Country   Salary
0  Rahim  Bangladesh  30000.0
3  Sakib  Bangladesh  50000.0

In [38]:
# ekhon bangladesh and japan er student dekhte chai
df.loc[
    (df['Country'] == 'Bangladesh') |
    (df['Country'] == 'Japan')
]

    Name     Country   Salary
0  Rahim  Bangladesh  30000.0
2  Jihad       Japan  45000.0
3  Sakib  Bangladesh  50000.0

In [39]:
# uporer code diyew kintu amra onekgula country er student dekhte parbo but aaro jodi condition ashto tahole code aaro boro hoye jeto. easy korar jonne amra isin() method use korte pari.

df.loc[df['Country'].isin(['Bangladesh', 'Japan'])]

    Name     Country   Salary
0  Rahim  Bangladesh  30000.0
2  Jihad       Japan  45000.0
3  Sakib  Bangladesh  50000.0

### isnull() method

In [43]:
# isnull() এর অর্থ "এই value কি NaN (empty)?"

# NaN hole true return korbe. NaN na hole false return korbe.

# ধরি, যাদের Salary নেই (NaN) তাদের বের করতে চাই।
df['Salary'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
Name: Salary, dtype: bool

In [44]:
df.loc[df['Salary'].isnull()]

    Name Country  Salary
1  Karim   India     NaN
4  Nabil     USA     NaN

### notnull() method

In [45]:
# eta isnull() method er ulta.

# যাদের Salary নেই (NaN) তাদের বের করতে চাই।
df.loc[df['Salary'].notnull()]

    Name     Country   Salary
0  Rahim  Bangladesh  30000.0
2  Jihad       Japan  45000.0
3  Sakib  Bangladesh  50000.0
5   Rafi         NaN  40000.0