# Pandas Dataframes

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = np.random.rand(6,5)
data

array([[0.38286994, 0.00401849, 0.5866201 , 0.03749221, 0.8365129 ],
       [0.33175279, 0.64670349, 0.69418595, 0.92265012, 0.18626562],
       [0.01163677, 0.26616294, 0.82827089, 0.58841489, 0.48900028],
       [0.14875104, 0.09359851, 0.68028266, 0.97515827, 0.78351688],
       [0.72433589, 0.3321796 , 0.04489528, 0.01359695, 0.29807645],
       [0.62676693, 0.72903021, 0.44694301, 0.71892972, 0.41279843]])

In [4]:
df = pd.DataFrame(data=data)
df

          0         1         2         3         4
0  0.382870  0.004018  0.586620  0.037492  0.836513
1  0.331753  0.646703  0.694186  0.922650  0.186266
2  0.011637  0.266163  0.828271  0.588415  0.489000
3  0.148751  0.093599  0.680283  0.975158  0.783517
4  0.724336  0.332180  0.044895  0.013597  0.298076
5  0.626767  0.729030  0.446943  0.718930  0.412798

## Dataframe selection(indexing) - 1

In [5]:
# dataframe hocche onekgula data series er column collection. mane onekgula data seriese ke column hishebe store korle sheta dataframe hoye jabe.

df[0] # etar maddhome first column(not first row) access pabo. data series e index(row er) and value thake only.

0    0.382870
1    0.331753
2    0.011637
3    0.148751
4    0.724336
5    0.626767
Name: 0, dtype: float64

In [6]:
# dataframe er protita column je ekta series tar prove:

type(df[0])

pandas.Series

In [7]:
df2 = pd.DataFrame(
    data = data,
    index = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.382870  0.004018  0.586620  0.037492  0.836513
row2  0.331753  0.646703  0.694186  0.922650  0.186266
row3  0.011637  0.266163  0.828271  0.588415  0.489000
row4  0.148751  0.093599  0.680283  0.975158  0.783517
row5  0.724336  0.332180  0.044895  0.013597  0.298076
row6  0.626767  0.729030  0.446943  0.718930  0.412798

In [8]:
df2['col1']

row1    0.382870
row2    0.331753
row3    0.011637
row4    0.148751
row5    0.724336
row6    0.626767
Name: col1, dtype: float64

In [9]:
# see multiple columns

df2[['col1', 'col2', 'col3']]

          col1      col2      col3
row1  0.382870  0.004018  0.586620
row2  0.331753  0.646703  0.694186
row3  0.011637  0.266163  0.828271
row4  0.148751  0.093599  0.680283
row5  0.724336  0.332180  0.044895
row6  0.626767  0.729030  0.446943

### add new column in datafram

In [10]:
# important: new column add korte element shongkha hote hobe row er shoman.

df2['new_col1'] = [1, 2, 3, 4, 5, 6]
df2['new_col2'] = np.random.rand(6)

df2

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.382870  0.004018  0.586620  0.037492  0.836513         1  0.571165
row2  0.331753  0.646703  0.694186  0.922650  0.186266         2  0.242777
row3  0.011637  0.266163  0.828271  0.588415  0.489000         3  0.122153
row4  0.148751  0.093599  0.680283  0.975158  0.783517         4  0.923552
row5  0.724336  0.332180  0.044895  0.013597  0.298076         5  0.647036
row6  0.626767  0.729030  0.446943  0.718930  0.412798         6  0.504284

## remove row and column from dataframe

In [11]:
# dy default drop method row ke delete kore. but eta main datafram ke modify kore na. new ekta dataframe return kore.
df2.drop('row3')

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.382870  0.004018  0.586620  0.037492  0.836513         1  0.571165
row2  0.331753  0.646703  0.694186  0.922650  0.186266         2  0.242777
row4  0.148751  0.093599  0.680283  0.975158  0.783517         4  0.923552
row5  0.724336  0.332180  0.044895  0.013597  0.298076         5  0.647036
row6  0.626767  0.729030  0.446943  0.718930  0.412798         6  0.504284

In [12]:
# column remove using drop method:

df2.drop(columns= 'new_col2')

          col1      col2      col3      col4      col5  new_col1
row1  0.382870  0.004018  0.586620  0.037492  0.836513         1
row2  0.331753  0.646703  0.694186  0.922650  0.186266         2
row3  0.011637  0.266163  0.828271  0.588415  0.489000         3
row4  0.148751  0.093599  0.680283  0.975158  0.783517         4
row5  0.724336  0.332180  0.044895  0.013597  0.298076         5
row6  0.626767  0.729030  0.446943  0.718930  0.412798         6

In [13]:
# upore drop method use kore row3 and new_col2 remove kora hoise. but main dataframe aager motoi ase. karon drop method main dataframe ke modify kore na. 

df2

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.382870  0.004018  0.586620  0.037492  0.836513         1  0.571165
row2  0.331753  0.646703  0.694186  0.922650  0.186266         2  0.242777
row3  0.011637  0.266163  0.828271  0.588415  0.489000         3  0.122153
row4  0.148751  0.093599  0.680283  0.975158  0.783517         4  0.923552
row5  0.724336  0.332180  0.044895  0.013597  0.298076         5  0.647036
row6  0.626767  0.729030  0.446943  0.718930  0.412798         6  0.504284

In [14]:
# main dataframe ke modify korte hole drop method er sathe inplace=True use korte hobe. 

df2.drop(columns= 'new_col2', inplace=True)
df2

          col1      col2      col3      col4      col5  new_col1
row1  0.382870  0.004018  0.586620  0.037492  0.836513         1
row2  0.331753  0.646703  0.694186  0.922650  0.186266         2
row3  0.011637  0.266163  0.828271  0.588415  0.489000         3
row4  0.148751  0.093599  0.680283  0.975158  0.783517         4
row5  0.724336  0.332180  0.044895  0.013597  0.298076         5
row6  0.626767  0.729030  0.446943  0.718930  0.412798         6

### remove row and column from dataframe using axis

In [15]:
df2

          col1      col2      col3      col4      col5  new_col1
row1  0.382870  0.004018  0.586620  0.037492  0.836513         1
row2  0.331753  0.646703  0.694186  0.922650  0.186266         2
row3  0.011637  0.266163  0.828271  0.588415  0.489000         3
row4  0.148751  0.093599  0.680283  0.975158  0.783517         4
row5  0.724336  0.332180  0.044895  0.013597  0.298076         5
row6  0.626767  0.729030  0.446943  0.718930  0.412798         6

In [16]:
# first e dataframe er shape(dimention) jante hobe.
df2.shape

(6, 6)

In [17]:
# dataframe er shape pailam (6,6). eta ekta tuple. so etaro index ase. first index row ke indicate kore and second index column ke indicate kore. 

# row delete:
df2.drop('row2', inplace = False, axis = 0) # row delete korbo tai axis = 0 dite hobe

          col1      col2      col3      col4      col5  new_col1
row1  0.382870  0.004018  0.586620  0.037492  0.836513         1
row3  0.011637  0.266163  0.828271  0.588415  0.489000         3
row4  0.148751  0.093599  0.680283  0.975158  0.783517         4
row5  0.724336  0.332180  0.044895  0.013597  0.298076         5
row6  0.626767  0.729030  0.446943  0.718930  0.412798         6

In [18]:
# column delete:
df2.drop('new_col1', inplace = False, axis = 1) # column delete korbo tai axis = 1 dite hobe

          col1      col2      col3      col4      col5
row1  0.382870  0.004018  0.586620  0.037492  0.836513
row2  0.331753  0.646703  0.694186  0.922650  0.186266
row3  0.011637  0.266163  0.828271  0.588415  0.489000
row4  0.148751  0.093599  0.680283  0.975158  0.783517
row5  0.724336  0.332180  0.044895  0.013597  0.298076
row6  0.626767  0.729030  0.446943  0.718930  0.412798

## Dataframe selection using loc and iloc

In [19]:
df3 = pd.DataFrame(
    data = np.random.randint(1, 100, size=(6, 5)),
    index = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5']
)

df3

      col1  col2  col3  col4  col5
row1    52    73    92    61    35
row2    50    44    61    71    43
row3    91    67    34    34    11
row4    83    83    95     8    45
row5    63    40    90    49    60
row6    41    28    18    96    34

### loc attribute

In [20]:
# loc means location
# loc syntax: df.loc[row_label, column_label]

# row select
df3.loc['row2'] # etaw ekta dataframe series return korbe.

col1    50
col2    44
col3    61
col4    71
col5    43
Name: row2, dtype: int64

In [ ]:
# column select using loc method.
df3.loc[:, 'col2'] 

# df3['col2']  ---> eta o same kaj korbe. but loc method use korle row aage select kore then column select korte hobe. real project e only column select korte hole evabei select kora hoy. but slicing or row lagle tokhon .loc method use kora hoy.

row1    73
row2    44
row3    67
row4    83
row5    40
row6    28
Name: col2, dtype: int64

In [ ]:
# multiple column select 
df3[['col2', 'col3']] 

# loc mthod: df3.loc[:, ['col2', 'col3']]

      col2  col3
row1    73    92
row2    44    61
row3    67    34
row4    83    95
row5    40    90
row6    28    18

In [23]:
# select specific value using loc method.
df3.loc['row2', 'col2']

np.int64(44)

In [24]:
df3

      col1  col2  col3  col4  col5
row1    52    73    92    61    35
row2    50    44    61    71    43
row3    91    67    34    34    11
row4    83    83    95     8    45
row5    63    40    90    49    60
row6    41    28    18    96    34

In [25]:
# ekhon ami 55,50, 97, 82 dekhte chai. mane row2 and row3 er col2 and col3 dekhte chai.

df3.loc[['row2', 'row3']]

      col1  col2  col3  col4  col5
row2    50    44    61    71    43
row3    91    67    34    34    11

In [26]:

df3.loc[['row2', 'row3'], ['col2', 'col3']]

      col2  col3
row2    44    61
row3    67    34

### iloc attribute

In [27]:
# iloc means integer location.

df3

      col1  col2  col3  col4  col5
row1    52    73    92    61    35
row2    50    44    61    71    43
row3    91    67    34    34    11
row4    83    83    95     8    45
row5    63    40    90    49    60
row6    41    28    18    96    34

In [28]:
# iloc diye jokhon selection korbo tokhon row and column ke integer value diye select korte hobe. also output ew row and column er nam integer value te show korbe.

# single element select:
df3.iloc[1, 1] # row2 and col2 er value show kor

np.int64(44)

In [29]:
# multiple row and column select:

df3.iloc[[1,2]]

      col1  col2  col3  col4  col5
row2    50    44    61    71    43
row3    91    67    34    34    11

In [30]:
df3.iloc[[1,2], [1,2]]

      col2  col3
row2    44    61
row3    67    34

### Choosing between loc and iloc (একটি গুরুত্বপূর্ণ পার্থক্য!)

`loc` এবং `iloc` এর মধ্যে কাজ করতে গেলে একটি বড় "gotcha" বা ফাঁদ আছে, যা মাথায় রাখা খুব জরুরি। এই দুটি মেথড ইনডেক্সিং করার সময় একটু ভিন্ন নিয়ম মেনে চলে।

* **`iloc`:** এটি Python-এর স্ট্যান্ডার্ড ইনডেক্সিং নিয়ম মেনে চলে। অর্থাৎ, রেঞ্জ দিলে প্রথমটি ইনক্লুড হয়, কিন্তু শেষেরটি এক্সক্লুড (বাদ) হয়ে যায়। তাই `0:10` দিলে এটি 0 থেকে 9 পর্যন্ত (মোট ১০টি) ভ্যালু সিলেক্ট করবে।
* **`loc`:** এটি **inclusively** (সবগুলো ধরে) ইনডেক্স করে। তাই `0:10` দিলে এটি 0 থেকে 10 পর্যন্ত (মোট ১১টি) ভ্যালু সিলেক্ট করবে!

**কেন এই পরিবর্তন?**
কারণ `loc` দিয়ে string বা টেক্সট ইনডেক্সও রেঞ্জ করা যায়। ধরুন, আপনার ইনডেক্সে 'Apples' থেকে 'Potatoes' পর্যন্ত অনেকগুলো নাম আছে। আপনি যদি `df.loc['Apples':'Potatoes']` লেখেন, তবে আপনি চাইবেন 'Potatoes' নামটিও লিস্টে থাকুক। যদি `iloc`-এর মতো কাজ করতো, তবে আপনাকে 'Potatoes'-এর পরের শব্দটি (যেমন 'Potatoet') খুঁজে বের করে লিখতে হতো, যা খুবই ঝামেলার।

এই নিয়মটি তখন খুব কনফিউজিং হয়ে যায়, যখন আপনার ইনডেক্সগুলো `0, 1, 2... 1000` নাম্বারে থাকে। `df.iloc[0:1000]` আপনাকে ঠিক 1000টি ডেটাই দেবে, কিন্তু `df.loc[0:1000]` আপনাকে 1001টি ডেটা দেবে! তাই `loc` দিয়ে ঠিক 1000টি ডেটা পেতে চাইলে আপনাকে এক ঘর কমিয়ে `df.loc[0:999]` লিখতে হবে।

## Conditional Selection

In [31]:
data= np.random.randn(8, 5)

df = pd.DataFrame(
    data=data,
    index=['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df

          col1      col2      col3      col4      col5
row1 -1.195945  0.341124 -1.205515  0.049327  0.549786
row2  0.808055  1.584874  1.020992  1.361825  0.568414
row3 -0.308215 -0.465813  1.723079  1.973564  0.037645
row4  1.422242  1.270291  1.418244  0.187461 -0.880002
row5 -0.227985  1.481573  0.801346 -0.406386  0.741436
row6 -1.734469 -2.348057  1.017848 -1.275414 -0.441347
row7 -0.677727 -0.122173 -0.963738 -2.158999  1.728752
row8 -0.072699 -0.406815  0.996949 -1.145810 -0.258586

In [32]:
# jei value gula 0 er theke boro tader dekhte chai

df[df>0]

          col1      col2      col3      col4      col5
row1       NaN  0.341124       NaN  0.049327  0.549786
row2  0.808055  1.584874  1.020992  1.361825  0.568414
row3       NaN       NaN  1.723079  1.973564  0.037645
row4  1.422242  1.270291  1.418244  0.187461       NaN
row5       NaN  1.481573  0.801346       NaN  0.741436
row6       NaN       NaN  1.017848       NaN       NaN
row7       NaN       NaN       NaN       NaN  1.728752
row8       NaN       NaN  0.996949       NaN       NaN

In [33]:
# column 3 er jei value gula 0 er theke boro tader dekhte chai
df[df['col3']>0]

          col1      col2      col3      col4      col5
row2  0.808055  1.584874  1.020992  1.361825  0.568414
row3 -0.308215 -0.465813  1.723079  1.973564  0.037645
row4  1.422242  1.270291  1.418244  0.187461 -0.880002
row5 -0.227985  1.481573  0.801346 -0.406386  0.741436
row6 -1.734469 -2.348057  1.017848 -1.275414 -0.441347
row8 -0.072699 -0.406815  0.996949 -1.145810 -0.258586

In [34]:
# multiple conditional selection:

# pandas e multi conditional selection e ektu careful thakte hobe. python or cpp te amra contion apply kori logical and, logical or diye. but pandas e kintu bitwise and(&), bitwise or(|) use korte hobe.

# like ami column 3 and column 5 both column er jei value gula positive shudhu tader dekhabe.

df[(df['col3']>0) & (df['col5']>0)] # biwsie operator use korte must be bracket dite hobe condition e.

          col1      col2      col3      col4      col5
row2  0.808055  1.584874  1.020992  1.361825  0.568414
row3 -0.308215 -0.465813  1.723079  1.973564  0.037645
row5 -0.227985  1.481573  0.801346 -0.406386  0.741436

In [35]:
# ami uporer code e  bitwise and(&) and use korsi. ami jodi logical and use kortam tahole error show korto.

df[(df['col3']>0) and (df['col5']>0)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# uporer error er reason holo logical and, logical or just boolean value niye kaj kore. but ekhane amra duita column er upor condition apply korsi. and ei column gula holo ekta series.

# so ekhane compare hocche: pandas series vs pandas series. tai amader bitwise operators use korte hobe.

type(df['col3']>0)

pandas.Series