# Pandas Dataframes

In [1]:
import numpy as np
import pandas as pd

In [7]:
data = np.random.rand(6,5)
data

array([[0.33611538, 0.58773976, 0.51792092, 0.53779706, 0.03122738],
       [0.19125573, 0.31067094, 0.12047996, 0.39305553, 0.45019729],
       [0.83468903, 0.21587398, 0.3053396 , 0.69087014, 0.21632906],
       [0.78717316, 0.82282241, 0.06360674, 0.89393282, 0.36044175],
       [0.97181734, 0.53918054, 0.02184201, 0.47654292, 0.78448951],
       [0.04434586, 0.64098619, 0.57750453, 0.96873369, 0.05494939]])

In [8]:
df = pd.DataFrame(data=data)
df

          0         1         2         3         4
0  0.336115  0.587740  0.517921  0.537797  0.031227
1  0.191256  0.310671  0.120480  0.393056  0.450197
2  0.834689  0.215874  0.305340  0.690870  0.216329
3  0.787173  0.822822  0.063607  0.893933  0.360442
4  0.971817  0.539181  0.021842  0.476543  0.784490
5  0.044346  0.640986  0.577505  0.968734  0.054949

## Dataframe selection(indexing) - 1

In [10]:
# dataframe hocche onekgula data series er column collection. mane onekgula data seriese ke column hishebe store korle sheta dataframe hoye jabe.

df[0] # etar maddhome first column(not first row) access pabo. data series e index(row er) and value thake only.

0    0.336115
1    0.191256
2    0.834689
3    0.787173
4    0.971817
5    0.044346
Name: 0, dtype: float64

In [11]:
# dataframe er protita column je ekta series tar prove:

type(df[0])

pandas.Series

In [13]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
    If ``data`` is DataFrame then is ignored.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {"col1": [1, 2], "col2": [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {"col1": [0, 1, 2, 3], "col2": pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(
...     np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"]
... )
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array(
...     [(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...     dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")],
... )
>>> df3 = pd.DataFrame(data, columns=["c", "a"])
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           ~/miniconda3/envs/ml_env/lib/python3.11/site-packages/pandas/__init__.py
Type:           type
Subclasses:     SubclassedDataFrame

In [14]:
df2 = pd.DataFrame(
    data = data,
    index = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.336115  0.587740  0.517921  0.537797  0.031227
row2  0.191256  0.310671  0.120480  0.393056  0.450197
row3  0.834689  0.215874  0.305340  0.690870  0.216329
row4  0.787173  0.822822  0.063607  0.893933  0.360442
row5  0.971817  0.539181  0.021842  0.476543  0.784490
row6  0.044346  0.640986  0.577505  0.968734  0.054949

In [16]:
df2['col1']

row1    0.336115
row2    0.191256
row3    0.834689
row4    0.787173
row5    0.971817
row6    0.044346
Name: col1, dtype: float64

In [19]:
# see multiple columns

df2[['col1', 'col2', 'col3']]

          col1      col2      col3
row1  0.336115  0.587740  0.517921
row2  0.191256  0.310671  0.120480
row3  0.834689  0.215874  0.305340
row4  0.787173  0.822822  0.063607
row5  0.971817  0.539181  0.021842
row6  0.044346  0.640986  0.577505

### add new column in datafram

In [ ]:
# important: new column add korte element shongkha hote hobe row er shoman.

df2['new_col1'] = [1, 2, 3, 4, 5, 6]
df2['new_col2'] = np.random.rand(6)

df2

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.336115  0.587740  0.517921  0.537797  0.031227         1  0.291891
row2  0.191256  0.310671  0.120480  0.393056  0.450197         2  0.568389
row3  0.834689  0.215874  0.305340  0.690870  0.216329         3  0.679635
row4  0.787173  0.822822  0.063607  0.893933  0.360442         4  0.652557
row5  0.971817  0.539181  0.021842  0.476543  0.784490         5  0.846062
row6  0.044346  0.640986  0.577505  0.968734  0.054949         6  0.332814

## remove row and column from dataframe

In [37]:
# dy default drop method row ke delete kore. but eta main datafram ke modify kore na. new ekta dataframe return kore.
df2.drop('row3')

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.336115  0.587740  0.517921  0.537797  0.031227         1  0.291891
row2  0.191256  0.310671  0.120480  0.393056  0.450197         2  0.568389
row4  0.787173  0.822822  0.063607  0.893933  0.360442         4  0.652557
row5  0.971817  0.539181  0.021842  0.476543  0.784490         5  0.846062
row6  0.044346  0.640986  0.577505  0.968734  0.054949         6  0.332814

In [38]:
# column remove using drop method:

df2.drop(columns= 'new_col2')

          col1      col2      col3      col4      col5  new_col1
row1  0.336115  0.587740  0.517921  0.537797  0.031227         1
row2  0.191256  0.310671  0.120480  0.393056  0.450197         2
row3  0.834689  0.215874  0.305340  0.690870  0.216329         3
row4  0.787173  0.822822  0.063607  0.893933  0.360442         4
row5  0.971817  0.539181  0.021842  0.476543  0.784490         5
row6  0.044346  0.640986  0.577505  0.968734  0.054949         6

In [41]:
# upore drop method use kore row3 and new_col2 remove kora hoise. but main dataframe aager motoi ase. karon drop method main dataframe ke modify kore na. 

df2

          col1      col2      col3      col4      col5  new_col1  new_col2
row1  0.336115  0.587740  0.517921  0.537797  0.031227         1  0.291891
row2  0.191256  0.310671  0.120480  0.393056  0.450197         2  0.568389
row3  0.834689  0.215874  0.305340  0.690870  0.216329         3  0.679635
row4  0.787173  0.822822  0.063607  0.893933  0.360442         4  0.652557
row5  0.971817  0.539181  0.021842  0.476543  0.784490         5  0.846062
row6  0.044346  0.640986  0.577505  0.968734  0.054949         6  0.332814

In [42]:
# main dataframe ke modify korte hole drop method er sathe inplace=True use korte hobe. 

df2.drop(columns= 'new_col2', inplace=True)
df2

          col1      col2      col3      col4      col5  new_col1
row1  0.336115  0.587740  0.517921  0.537797  0.031227         1
row2  0.191256  0.310671  0.120480  0.393056  0.450197         2
row3  0.834689  0.215874  0.305340  0.690870  0.216329         3
row4  0.787173  0.822822  0.063607  0.893933  0.360442         4
row5  0.971817  0.539181  0.021842  0.476543  0.784490         5
row6  0.044346  0.640986  0.577505  0.968734  0.054949         6

### remove row and column from dataframe using axis

In [43]:
df2

          col1      col2      col3      col4      col5  new_col1
row1  0.336115  0.587740  0.517921  0.537797  0.031227         1
row2  0.191256  0.310671  0.120480  0.393056  0.450197         2
row3  0.834689  0.215874  0.305340  0.690870  0.216329         3
row4  0.787173  0.822822  0.063607  0.893933  0.360442         4
row5  0.971817  0.539181  0.021842  0.476543  0.784490         5
row6  0.044346  0.640986  0.577505  0.968734  0.054949         6

In [44]:
# first e dataframe er shape(dimention) jante hobe.
df2.shape

(6, 6)

In [46]:
# dataframe er shape pailam (6,6). eta ekta tuple. so etaro index ase. first index row ke indicate kore and second index column ke indicate kore. 

# row delete:
df2.drop('row2', inplace = False, axis = 0) # row delete korbo tai axis = 0 dite hobe

          col1      col2      col3      col4      col5  new_col1
row1  0.336115  0.587740  0.517921  0.537797  0.031227         1
row3  0.834689  0.215874  0.305340  0.690870  0.216329         3
row4  0.787173  0.822822  0.063607  0.893933  0.360442         4
row5  0.971817  0.539181  0.021842  0.476543  0.784490         5
row6  0.044346  0.640986  0.577505  0.968734  0.054949         6

In [47]:
# column delete:
df2.drop('new_col1', inplace = False, axis = 1) # column delete korbo tai axis = 1 dite hobe

          col1      col2      col3      col4      col5
row1  0.336115  0.587740  0.517921  0.537797  0.031227
row2  0.191256  0.310671  0.120480  0.393056  0.450197
row3  0.834689  0.215874  0.305340  0.690870  0.216329
row4  0.787173  0.822822  0.063607  0.893933  0.360442
row5  0.971817  0.539181  0.021842  0.476543  0.784490
row6  0.044346  0.640986  0.577505  0.968734  0.054949

## Dataframe selection using loc and iloc

In [51]:
df3 = pd.DataFrame(
    data = np.random.randint(1, 100, size=(6, 5)),
    index = ['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5']
)

df3

      col1  col2  col3  col4  col5
row1    33    22    15    82    90
row2    77    55    50    80    89
row3     5    97    82    27    90
row4    20    72    84    52    54
row5    45    59    72    10    58
row6    16    75     9    33    42

### loc attribute

In [ ]:
# loc means location

# row select
df3.loc['row2'] # etaw ekta dataframe series return korbe.

col1    77
col2    55
col3    50
col4    80
col5    89
Name: row2, dtype: int64

In [53]:
# column select
df3['col2'] # etaw ekta dataframe series return korbe.

row1    22
row2    55
row3    97
row4    72
row5    59
row6    75
Name: col2, dtype: int64

In [54]:
# row and column select
df3.loc['row2', 'col2']

np.int64(55)

In [55]:
df3

      col1  col2  col3  col4  col5
row1    33    22    15    82    90
row2    77    55    50    80    89
row3     5    97    82    27    90
row4    20    72    84    52    54
row5    45    59    72    10    58
row6    16    75     9    33    42

In [58]:
# ekhon ami 55,50, 97, 82 dekhte chai. mane row2 and row3 er col2 and col3 dekhte chai.

df3.loc[['row2', 'row3']]

      col1  col2  col3  col4  col5
row2    77    55    50    80    89
row3     5    97    82    27    90

In [59]:

df3.loc[['row2', 'row3'], ['col2', 'col3']]

      col2  col3
row2    55    50
row3    97    82

### iloc attribute

In [60]:
# iloc means integer location.

df3

      col1  col2  col3  col4  col5
row1    33    22    15    82    90
row2    77    55    50    80    89
row3     5    97    82    27    90
row4    20    72    84    52    54
row5    45    59    72    10    58
row6    16    75     9    33    42

In [62]:
# iloc diye jokhon selection korbo tokhon row and column ke integer value diye select korte hobe. also output ew row and column er nam integer value te show korbe.

# single element select:
df3.iloc[1, 1] # row2 and col2 er value show kor

np.int64(55)

In [64]:
# multiple row and column select:

df3.iloc[[1,2]]

      col1  col2  col3  col4  col5
row2    77    55    50    80    89
row3     5    97    82    27    90

In [65]:
df3.iloc[[1,2], [1,2]]

      col2  col3
row2    55    50
row3    97    82

## Conditional Selection

In [66]:
data= np.random.randn(8, 5)

df = pd.DataFrame(
    data=data,
    index=['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df

          col1      col2      col3      col4      col5
row1  0.646612  0.988697 -1.809062  0.726568  0.109740
row2  0.932471 -0.147338  0.171272 -0.328676  2.068309
row3  0.281094 -0.284873 -1.805536  0.320845  0.381124
row4  1.366122  0.595908  0.287294 -0.055858 -1.071405
row5  0.567990  0.417947  0.234001  1.613208  0.572842
row6 -0.143518 -0.384384 -0.370496 -0.539667  1.342463
row7 -0.802305 -0.810952 -1.789088  0.224585  1.006037
row8  2.338935 -0.498996 -1.705303  0.146896  0.212593

In [67]:
# jei value gula 0 er theke boro tader dekhte chai

df[df>0]

          col1      col2      col3      col4      col5
row1  0.646612  0.988697       NaN  0.726568  0.109740
row2  0.932471       NaN  0.171272       NaN  2.068309
row3  0.281094       NaN       NaN  0.320845  0.381124
row4  1.366122  0.595908  0.287294       NaN       NaN
row5  0.567990  0.417947  0.234001  1.613208  0.572842
row6       NaN       NaN       NaN       NaN  1.342463
row7       NaN       NaN       NaN  0.224585  1.006037
row8  2.338935       NaN       NaN  0.146896  0.212593

In [68]:
# column 3 er jei value gula 0 er theke boro tader dekhte chai
df[df['col3']>0]

          col1      col2      col3      col4      col5
row2  0.932471 -0.147338  0.171272 -0.328676  2.068309
row4  1.366122  0.595908  0.287294 -0.055858 -1.071405
row5  0.567990  0.417947  0.234001  1.613208  0.572842

In [ ]:
# multiple conditional selection:

# pandas e multi conditional selection e ektu careful thakte hobe. python or cpp te amra contion apply kori logical and, logical or diye. but pandas e kintu bitwise and(&), bitwise or(|) use korte hobe.

# like ami column 3 and column 5 both column er jei value gula positive shudhu tader dekhabe.

df[(df['col3']>0) & (df['col5']>0)] # biwsie operator use korte must be bracket dite hobe condition e.

          col1      col2      col3      col4      col5
row2  0.932471 -0.147338  0.171272 -0.328676  2.068309
row5  0.567990  0.417947  0.234001  1.613208  0.572842

In [ ]:
# ami uporer code e  bitwise and(&) and use korsi. ami jodi logical and use kortam tahole error show korto.

df[(df['col3']>0) and (df['col5']>0)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# uporer error er reason holo logical and, logical or just boolean value niye kaj kore. but ekhane amra duita column er upor condition apply korsi. and ei column gula holo ekta series.

# so ekhane compare hocche: pandas series vs pandas series. tai amader bitwise operators use korte hobe.

type(df['col3']>0)

pandas.Series