In [1]:
import pandas as pd
import numpy as np

In [2]:
groups = ['group1'] * 3 + ['group2'] * 3
groups

['group1', 'group1', 'group1', 'group2', 'group2', 'group2']

In [3]:
inside_groups = ['row1', 'row2', 'row3'] * 2
inside_groups

['row1', 'row2', 'row3', 'row1', 'row2', 'row3']

In [4]:
# zip() function duita list ke combine kore tuple banay.

zip(groups, inside_groups)

In [5]:
# only zip() function use korle amake just ekta object er memory location dekhabe. but ami jodi list() function er moddhe zip() function ke use kori tahole amake tuple er list dekhabe.

tup = list(zip(groups, inside_groups))
tup

[('group1', 'row1'),
 ('group1', 'row2'),
 ('group1', 'row3'),
 ('group2', 'row1'),
 ('group2', 'row2'),
 ('group2', 'row3')]

In [6]:
# ekhn ami ei list ke multiindex e convert korbo.

mul_index = pd.MultiIndex.from_tuples(tuples= tup)
mul_index

MultiIndex([('group1', 'row1'),
            ('group1', 'row2'),
            ('group1', 'row3'),
            ('group2', 'row1'),
            ('group2', 'row2'),
            ('group2', 'row3')],
           )

In [7]:
# ekhon ei multiindex ke ami ekta dataframe e convert korle shundor ekta table dekhbo.

df = pd.DataFrame(
    data = np.random.randn(6, 2),
    index = mul_index,
    columns = ['col1', 'col2']
)

df

                 col1      col2
group1 row1  0.146800 -0.297517
       row2 -0.838271 -1.396283
       row3  0.780751 -0.865402
group2 row1  0.954539 -0.383874
       row2  0.708071  0.127268
       row3  0.657010 -0.038480

In [9]:
# amra etokhon dhore ei table or dataset ta banailam. real life e eirokom dataset amra khub komi pabo. but oi dui ekbar jodi pai tokhon kivabe indexing korbo ta shekhar jonnei ei table ta eto jhamela kore banailam.

# ekhon group1 er row1 er value gula dekhbo.

df.loc['group1', 'row1']

col1    0.146800
col2   -0.297517
Name: (group1, row1), dtype: float64

In [12]:
# ami group1 er row1 and group2 er row1 er value gula dekhte chai. 
df.loc[('group1', 'row1'), ('group2', 'row1')] # evabe access kora jabe na. error ashbe. solution hishbe ami group column er nam and row column er nam define kore dibo. then nam dhore indexing korbo.

KeyError: "None of [Index(['group2', 'row1'], dtype='str')] are in the [columns]"

In [14]:
df.index.names = ['groups', 'rows']
df

                 col1      col2
groups rows
group1 row1  0.146800 -0.297517
       row2 -0.838271 -1.396283
       row3  0.780751 -0.865402
group2 row1  0.954539 -0.383874
       row2  0.708071  0.127268
       row3  0.657010 -0.038480

In [17]:
# ekhon cross section method (xs) use kore ami group wise alada alada indexing korte parbo.

# level er nam dhore xs method e indexing kora jay.

df.xs('row1', level='rows')

            col1      col2
groups
group1  0.146800 -0.297517
group2  0.954539 -0.383874