In [1]:
import pandas as pd
import numpy as np

# Sample Dataset
data = {
    "Name": ["Jihad", "Safia", "Rahim", "Karim"],
    "Department": ["CSE", np.nan, "EEE", "BBA"],
    "Score": [85, np.nan, 90, 78],
    "Age": [22, 21, np.nan, 23]
}

df = pd.DataFrame(data)

df

    Name Department  Score   Age
0  Jihad        CSE   85.0  22.0
1  Safia        NaN    NaN  21.0
2  Rahim        EEE   90.0   NaN
3  Karim        BBA   78.0  23.0

## 1. Missing Value খুঁজে বের করা

In [2]:
# পুরো DataFrame-এ কোন cell-এ Missing Value আছে দেখো
df.isnull()

    Name  Department  Score    Age
0  False       False  False  False
1  False        True   True  False
2  False       False  False   True
3  False       False  False  False

In [3]:
# পুরো DataFrame-এ কোন cell Missing না
df.notnull()

   Name  Department  Score    Age
0  True        True   True   True
1  True       False  False   True
2  True        True   True  False
3  True        True   True   True

### নির্দিষ্ট Column-এর Missing Value বের করা

In [4]:
# Department column-এর যেসব row-তে NaN আছে
df[pd.isnull(df["Department"])]

    Name Department  Score   Age
1  Safia        NaN    NaN  21.0

In [5]:
# Department column-এর যেসব row-তে NaN নেই
df[pd.notnull(df["Department"])]

    Name Department  Score   Age
0  Jihad        CSE   85.0  22.0
2  Rahim        EEE   90.0   NaN
3  Karim        BBA   78.0  23.0

## 2. প্রতিটি Column-এ কতগুলো Missing Value আছে

In [6]:
# প্রতিটি column-এ কতটি NaN আছে
df.isnull().sum()

Name          0
Department    1
Score         1
Age           1
dtype: int64

## 3. Missing Value Delete করা

In [7]:
# NaN থাকা সব Row Delete

# যেসব row-তে অন্তত একটি NaN আছে, সেগুলো delete

df.dropna()

    Name Department  Score   Age
0  Jihad        CSE   85.0  22.0
3  Karim        BBA   78.0  23.0

In [8]:
# NaN থাকা সব Column Delete

# যেসব column-এ অন্তত একটি NaN আছে, সেগুলো delete
df.dropna(axis=1)

    Name
0  Jihad
1  Safia
2  Rahim
3  Karim

In [10]:
'''
    - Column delete করা শেষ option।

    - শুধু NaN আছে বলে Column delete করা উচিত না।

    - প্রথমে দেখতে হবে:
        i) Column কতটা গুরুত্বপূর্ণ।
        ii) কত % Missing Value আছে।
        iii) অন্যভাবে Fill করা সম্ভব কিনা।
'''

pass

## 4. Missing Value Fill করা

In [11]:
# সব NaN-এর জায়গায় "Missing" বসানো
df.fillna("Missing")

    Name Department    Score      Age
0  Jihad        CSE     85.0     22.0
1  Safia    Missing  Missing     21.0
2  Rahim        EEE     90.0  Missing
3  Karim        BBA     78.0     23.0

### নির্দিষ্ট Column Fill করা

In [12]:
# Department column-এর NaN-এ Unknown বসানো
df.fillna({
    "Department": "Unknown"
})

    Name Department  Score   Age
0  Jihad        CSE   85.0  22.0
1  Safia    Unknown    NaN  21.0
2  Rahim        EEE   90.0   NaN
3  Karim        BBA   78.0  23.0

In [13]:
# Score column-এর NaN-এ 0 বসানো
df.fillna({
    "Score": 0
})

    Name Department  Score   Age
0  Jihad        CSE   85.0  22.0
1  Safia        NaN    0.0  21.0
2  Rahim        EEE   90.0   NaN
3  Karim        BBA   78.0  23.0

### একাধিক Column একসাথে Fill করা

In [14]:
# Department এবং Score একসাথে Fill করা
df.fillna({
    "Department": "Unknown",
    "Score": 0
})

    Name Department  Score   Age
0  Jihad        CSE   85.0  22.0
1  Safia    Unknown    0.0  21.0
2  Rahim        EEE   90.0   NaN
3  Karim        BBA   78.0  23.0

## 5. Mean দিয়ে Fill করা

In [15]:
# Score column-এর Mean দিয়ে NaN Fill করা
df.fillna({
    "Score": df["Score"].mean()
})

    Name Department      Score   Age
0  Jihad        CSE  85.000000  22.0
1  Safia        NaN  84.333333  21.0
2  Rahim        EEE  90.000000   NaN
3  Karim        BBA  78.000000  23.0

In [16]:
# Age column-এর Mean দিয়ে NaN Fill করা
df.fillna({
    "Age": df["Age"].mean()
})

    Name Department  Score   Age
0  Jihad        CSE   85.0  22.0
1  Safia        NaN    NaN  21.0
2  Rahim        EEE   90.0  22.0
3  Karim        BBA   78.0  23.0

### একাধিক Numerical Column Mean দিয়ে Fill

In [17]:
# Score এবং Age-এর NaN Mean দিয়ে Fill
df.fillna({
    "Score": df["Score"].mean(),
    "Age": df["Age"].mean()
})

    Name Department      Score   Age
0  Jihad        CSE  85.000000  22.0
1  Safia        NaN  84.333333  21.0
2  Rahim        EEE  90.000000  22.0
3  Karim        BBA  78.000000  23.0

## 6. replace()

In [18]:
# replace() Missing Value-এর জন্য না। এটা Existing Value পরিবর্তন করার জন্য।

# single value replace

# BBA কে Business দিয়ে Replace
df["Department"].replace(
    "BBA",
    "Business"
)

0         CSE
1         NaN
2         EEE
3    Business
Name: Department, dtype: str

In [19]:
# multiple value replace

# একাধিক Value একসাথে Replace
df.replace({
    "Department": {
        "BBA": "Business",
        "EEE": "Electrical"
    }
})

    Name  Department  Score   Age
0  Jihad         CSE   85.0  22.0
1  Safia         NaN    NaN  21.0
2  Rahim  Electrical   90.0   NaN
3  Karim    Business   78.0  23.0

### Interview / Exam Important Methods

| Method           | কাজ                                     |
| ---------------- | --------------------------------------- |
| `isnull()`       | Missing Value খুঁজে বের করা             |
| `notnull()`      | Non-Missing Value খুঁজে বের করা         |
| `isnull().sum()` | প্রতিটি Column-এ কতটি Missing Value আছে |
| `dropna()`       | Missing Value থাকা Row/Column Delete    |
| `fillna()`       | Missing Value Fill করা                  |
| `replace()`      | Existing Value পরিবর্তন করা             |

---

### Professional Workflow

```text
Load Dataset
      ↓
Check Missing Value
(df.isnull().sum())
      ↓
Analyze Missing Percentage
      ↓
Numerical?
      ↓
Mean / Median Fill
      ↓
Categorical?
      ↓
Unknown / Mode Fill
      ↓
Need Value Change?
      ↓
replace()
      ↓
Only if Necessary
      ↓
dropna()
```