In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'A': [1, 2, np.nan, 3],
    'B': [2, np.nan, np.nan, 4],
    'C':[7,5,6,8]
}

df = pd.DataFrame(data=data)
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

## dropna()

In [4]:
# real life e real dataset niye kaj korte gele. hajar hajar or lakh lakh column er dataset hote pare and oi dataset er moddhe onek column er data ei NaN or empty value or missing value thaktei pare.

# missing value er poriman kom hole amra oi column gula delete kore dite pari. ekhane dropna() method use kora hoy.

# dropna() by default database er shob NaN value er er row gula delete kore dey.

df.dropna()

     A    B  C
0  1.0  2.0  7
3  3.0  4.0  8

In [5]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

In [9]:
# axis use kore set kore dewa jay ami row delete korbo naki column korbo.

# note: real life e dataset theke column delete na korai valo. ekta column delete korte hole onek kichu consider kore then dicision nibo. and jodi dekhi oi column na ekebarei kajer na tokhon tokhon drop method use kore column delete korbo. dropna() use kore column delete na korai valo.
  
df.dropna(axis=1, inplace=False) # axis = 0 mane row. axis = 1 mane column.

   C
0  7
1  5
2  6
3  8

In [7]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

## threshold in dropna() method

In [12]:
# threshold holo amar dataset e minimum koyta non-empty value thakle ami oita remove korbo na erokom condition dewa. etar jonne thresh use kora hoy.

# axis = 0 mane row. and thresh = 3 mane minimum 3 ta non-empty value thakle ami oita remove korbo na. jodi 3 tar kom non-empty value thake then oi row delete hoye jabe.

# amader dataset e row1 e 3 ta non-empty value ache. row2 e 1 ta non-empty value ache. row3 e 1 ta non-empty value ache. row4 e 3 ta non-empty value ache. so row2 and row3 delete hoye jabe.

# shortcut e mone rakhba. thresh = 3 mane amar minimum 3 ta real value thakte hobe.

df.dropna(axis=0, thresh=3)

     A    B  C
0  1.0  2.0  7
3  3.0  4.0  8

## fillna() method

In [14]:
# dataset e missing value gula ke fill up korar jonne fillna() method use kora hoy. fillna() method er moddhe ami je value ta dibo oi value diye missing value gula ke fill up kore dibe.

df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  5
2  NaN  NaN  6
3  3.0  4.0  8

In [15]:
df.fillna('missing')

         A        B  C
0      1.0      2.0  7
1      2.0  missing  5
2  missing  missing  6
3      3.0      4.0  8

In [18]:
# but real life e amra ekta numerical value diye ei missing value gula fill kore dei.

# ami jodi ekta column er missing value fill korte chai tahole:

df.fillna({'A': 0, 'B': 0}) # column er nam and then value dictionary hishbe pathaite hobe. ekhane ami A and B column er missing value gula ke 0 diye fill up korechi.

     A    B  C
0  1.0  2.0  7
1  2.0  0.0  5
2  0.0  0.0  6
3  3.0  4.0  8

In [19]:
# ekhon ami chai 0 diye replace na kore oi column er baki value gular mean ja hobe oi mean diye oi column er missing value fill kore dibo.

df.fillna({'A': df['A'].mean(), 'B': df['B'].mean()}) # ekhane ami A and B column er missing value gula ke oi column er mean diye fill up korechi.

     A    B  C
0  1.0  2.0  7
1  2.0  3.0  5
2  2.0  3.0  6
3  3.0  4.0  8