In [2]:
import pandas as pd

# Sample Dataset
df = pd.DataFrame({
    "Department": ["CSE","CSE","CSE","EEE","EEE","EEE","BBA","BBA","BBA","CSE","EEE","BBA"],
    "Section":    ["A","A","B","A","A","B","A","B","B","B","B","A"],
    "Student":    ["Rahim","Karim","Sakib","Mina","Rita","Nabil","Hasan","Jony","Nila","Tanim","Farhan","Sadia"],
    "Marks":      [80,92,75,88,70,95,78,84,91,86,82,89],
    "Attendance": [90,95,82,88,80,97,85,87,94,91,86,93]
})

df

   Department Section Student  Marks  Attendance
0         CSE       A   Rahim     80          90
1         CSE       A   Karim     92          95
2         CSE       B   Sakib     75          82
3         EEE       A    Mina     88          88
4         EEE       A    Rita     70          80
5         EEE       B   Nabil     95          97
6         BBA       A   Hasan     78          85
7         BBA       B    Jony     84          87
8         BBA       B    Nila     91          94
9         CSE       B   Tanim     86          91
10        EEE       B  Farhan     82          86
11        BBA       A   Sadia     89          93

##  1.Create Group

In [3]:
# শুধু group তৈরি করবে
df.groupby("Department")

# Output হবে DataFrameGroupBy object। কারণ এখনও কোনো operation করা হয়নি।

In [4]:
# প্রতিটি group দেখতে
for name, group in df.groupby("Department"):
    print(name)
    print(group)

BBA
   Department Section Student  Marks  Attendance
6         BBA       A   Hasan     78          85
7         BBA       B    Jony     84          87
8         BBA       B    Nila     91          94
11        BBA       A   Sadia     89          93
CSE
  Department Section Student  Marks  Attendance
0        CSE       A   Rahim     80          90
1        CSE       A   Karim     92          95
2        CSE       B   Sakib     75          82
9        CSE       B   Tanim     86          91
EEE
   Department Section Student  Marks  Attendance
3         EEE       A    Mina     88          88
4         EEE       A    Rita     70          80
5         EEE       B   Nabil     95          97
10        EEE       B  Farhan     82          86

## 2. single column grouping operations

In [5]:
# Department-wise মোট Marks
df.groupby("Department")["Marks"].sum()

# Department-wise Average Marks
df.groupby("Department")["Marks"].mean()

# Department-wise Highest Marks
df.groupby("Department")["Marks"].max()

# Department-wise Lowest Marks
df.groupby("Department")["Marks"].min()

# Department-wise Student Count
df.groupby("Department")["Marks"].count()

pass

In [6]:
df.groupby("Department")["Marks"].sum()

Department
BBA    342
CSE    333
EEE    335
Name: Marks, dtype: int64

## 3. Multiple Column Grouping

In [15]:
# Department + Section অনুযায়ী Marks এর Sum
df.groupby(["Department", "Section"])["Marks"].sum()

Department  Section
BBA         A          167
            B          175
CSE         A          172
            B          161
EEE         A          158
            B          177
Name: Marks, dtype: int64

## 4. Multiple Aggregation

In [8]:
# একই সাথে একাধিক statistics
df.groupby("Department")["Marks"].agg([
    "count",
    "sum",
    "mean",
    "min",
    "max"
])

            count  sum   mean  min  max
Department
BBA             4  342  85.50   78   91
CSE             4  333  83.25   75   92
EEE             4  335  83.75   70   95

## 5. Multiple Numeric Columns

In [9]:
# Marks এবং Attendance এর Average
df.groupby("Department")[["Marks", "Attendance"]].mean()

            Marks  Attendance
Department
BBA         85.50       89.75
CSE         83.25       89.50
EEE         83.75       87.75

## 6. Highest Marks Student

In [16]:
# প্রতিটি Department-এর Highest Marks Student-এর index
idx = df.groupby("Department")["Marks"].idxmax()

# সেই row গুলো বের করা
df.loc[idx][["Department", "Student", "Marks"]]

  Department Student  Marks
8        BBA    Nila     91
1        CSE   Karim     92
5        EEE   Nabil     95

## 7. Highest Student (Multiple Group)

In [11]:
# Department + Section অনুযায়ী Highest Marks Student
idx = df.groupby(["Department", "Section"])["Marks"].idxmax()

df.loc[idx]

   Department Section Student  Marks  Attendance
11        BBA       A   Sadia     89          93
8         BBA       B    Nila     91          94
1         CSE       A   Karim     92          95
9         CSE       B   Tanim     86          91
3         EEE       A    Mina     88          88
5         EEE       B   Nabil     95          97

## 8. Useful Methods

In [13]:
# প্রতিটি group-এ মোট row
df.groupby("Department").size()

# নির্দিষ্ট group দেখা
df.groupby("Department").get_group("CSE")

# Group অনুযায়ী index
df.groupby("Department").groups

# MultiIndex কে normal DataFrame বানানো
df.groupby(["Department", "Section"])["Marks"].sum().reset_index()

# Average Marks অনুযায়ী Sort
df.groupby("Department")["Marks"].mean().sort_values(ascending=False)

pass