In [1]:
import numpy as np
import pandas as pd

In [2]:
students = pd.DataFrame({
    "student_id": ["s1", "s2", "s3", "s4", "s5"],
    "name": ["Jihad", "Rahim", "Karim", "Nabil", "Asha"],
    "department_id": [101, 102, 103, 104, 105]
})

departments = pd.DataFrame({
    "department_id": [101, 102, 104, 106],
    "department_name": ["CSE", "EEE", "BBA", "English"],
    "building": ["A", "B", "C", "D"]
})

In [11]:
students

  student_id   name  department_id
0         s1  Jihad            101
1         s2  Rahim            102
2         s3  Karim            103
3         s4  Nabil            104
4         s5   Asha            105

In [12]:
departments

   department_id department_name building
0            101             CSE        A
1            102             EEE        B
2            104             BBA        C
3            106         English        D

## merge method

In [5]:
# inner join
students.merge(departments, on="department_id", how="inner")

  student_id   name  department_id department_name building
0         s1  Jihad            101             CSE        A
1         s2  Rahim            102             EEE        B
2         s4  Nabil            104             BBA        C

In [6]:
# inner join ke evabew likha jay:

pd.merge(students, departments, on="department_id", how="inner")

# output same ashbe. but uporer ta beshi use kora hoy. uporer ta etari short form.

  student_id   name  department_id department_name building
0         s1  Jihad            101             CSE        A
1         s2  Rahim            102             EEE        B
2         s4  Nabil            104             BBA        C

In [7]:
# left join
# jei table theke dataframe call kora hoy oita always left table.

# students = left table, departments = right table
students.merge(departments, on="department_id", how="left")

  student_id   name  department_id department_name building
0         s1  Jihad            101             CSE        A
1         s2  Rahim            102             EEE        B
2         s3  Karim            103             NaN      NaN
3         s4  Nabil            104             BBA        C
4         s5   Asha            105             NaN      NaN

In [8]:
# right join

# students = left table, departments = right table
students.merge(departments, on="department_id", how="right")

  student_id   name  department_id department_name building
0         s1  Jihad            101             CSE        A
1         s2  Rahim            102             EEE        B
2         s4  Nabil            104             BBA        C
3        NaN    NaN            106         English        D

In [9]:
#outer join
students.merge(departments, on="department_id", how="outer")

  student_id   name  department_id department_name building
0         s1  Jihad            101             CSE        A
1         s2  Rahim            102             EEE        B
2         s3  Karim            103             NaN      NaN
3         s4  Nabil            104             BBA        C
4         s5   Asha            105             NaN      NaN
5        NaN    NaN            106         English        D

In [10]:
# join method amra khub beshi use korbo na. tai dekhar dorkar nai. join method diye ja korbo tar shobi amra merge method diye korte parbo.

# join er index:
students.join(
    departments.set_index("department_id"),
    on="department_id"
)

  student_id   name  department_id department_name building
0         s1  Jihad            101             CSE        A
1         s2  Rahim            102             EEE        B
2         s3  Karim            103             NaN      NaN
3         s4  Nabil            104             BBA        C
4         s5   Asha            105             NaN      NaN

## concat method

In [13]:
'''
concat বনাম join সহজে মনে রাখার উপায়:

    - concat(): অনেকটা লেগো (Lego) ব্লকের মতো। যদি ব্লকগুলোর সাইজ (কলামের নাম) একই হয়, তবে একটার ওপর আরেকটা বসিয়ে একটি বড় বিল্ডিং বানিয়ে ফেলা যায়।

    - join(): এটি অনেকটা বিয়ের ঘটকালির মতো! দুটি আলাদা টেবিলে যদি একটি কমন জিনিস বা বৈশিষ্ট্য (যেমন: স্টুডেন্ট আইডি বা ভিডিওর টাইটেল) মিলে যায়, তবে সেই কমন জিনিসের ওপর ভিত্তি করে দুটি টেবিলকে পাশাপাশি বসিয়ে দেওয়া হয়।
'''

pass

In [14]:
# সেকশন A এর ডেটা
section_a = pd.DataFrame({'Name': ['Jihad', 'Safia'], 'Dept': ['CSE', 'BGE']})

# সেকশন B এর ডেটা
section_b = pd.DataFrame({'Name': ['Rahim', 'Karim'], 'Dept': ['EEE', 'CSE']})

In [15]:
section_a

    Name Dept
0  Jihad  CSE
1  Safia  BGE

In [16]:
section_b

    Name Dept
0  Rahim  EEE
1  Karim  CSE

In [17]:
# concat করে একসাথে করা
all_students = pd.concat([section_a, section_b], ignore_index=True)

print(all_students)

    Name Dept
0  Jihad  CSE
1  Safia  BGE
2  Rahim  EEE
3  Karim  CSE

## Pandas: `join()` vs `merge()`

দুটোই একাধিক DataFrame একসাথে যুক্ত (combine) করার জন্য ব্যবহৃত হয়। পার্থক্য হলো **কোন ভিত্তিতে (key) DataFrame-গুলোকে মিলানো হচ্ছে।**

---

### `merge()`

- **Column-এর ভিত্তিতে** DataFrame যুক্ত করে।
- SQL-এর `JOIN`-এর মতো কাজ করে।
- Pandas-এ সবচেয়ে বেশি ব্যবহৃত হয়।

### Example

**students**

| ID | Name |
|---:|------|
| 1 | Jihad |
| 2 | Rahim |
| 3 | Karim |

**marks**

| ID | Marks |
|---:|------:|
| 1 | 90 |
| 2 | 85 |
| 3 | 95 |

```python
students.merge(marks, on="ID")
```

Result:

| ID | Name | Marks |
|---:|------|------:|
| 1 | Jihad | 90 |
| 2 | Rahim | 85 |
| 3 | Karim | 95 |

---

### `join()`

- **Index-এর ভিত্তিতে** DataFrame যুক্ত করে।
- সাধারণত দুই DataFrame-এর Index আগে থেকেই সম্পর্কিত থাকলে ব্যবহার করা হয়।

### Example

```python
students.join(marks)
```

যদি উভয় DataFrame-এর Index একই হয়।

Result:

| Index | Name | Marks |
|------:|------|------:|
| 0 | Jihad | 90 |
| 1 | Rahim | 85 |
| 2 | Karim | 95 |

---

### `merge()` vs `join()`

| Feature | `merge()` | `join()` |
|---------|-----------|----------|
| Match based on | Column | Index |
| Default key | Common column | Index |
| SQL JOIN-এর মতো | Yes | Similar |
| সবচেয়ে বেশি ব্যবহৃত | Yes | No |
| `set_index()` লাগে? | No | কখনও কখনও |
| Best use case | Common column থাকলে | Data আগে থেকেই indexed থাকলে |

---

### কখন কোনটি ব্যবহার করবে?

| পরিস্থিতি | Method |
|-----------|--------|
| দুই DataFrame-এ common column আছে | `merge()` |
| দুই DataFrame-এর Index একই | `join()` |
| SQL JOIN-এর মতো কাজ করতে চাও | `merge()` |
| Index align করে combine করতে চাও | `join()` |

---