In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'col1': np.random.randint(1,10, size=10),
    'col2': np.random.randint(100,500, size=10),
    'col3': np.random.choice(['steve', 'jon', 'safia', 'jihad'], size=10)
})

df

   col1  col2   col3
0     8   375    jon
1     1   343  safia
2     1   287  jihad
3     9   463  jihad
4     4   495  jihad
5     6   188    jon
6     3   105  jihad
7     5   236  steve
8     3   234    jon
9     7   251  jihad

## 4 mathods that always have to use of any dataset to get info

### 1. head() and tail() method

In [2]:
# df.head()  it returns the first 5 rows of the dataframe
df.head()

   col1  col2   col3
0     8   375    jon
1     1   343  safia
2     1   287  jihad
3     9   463  jihad
4     4   495  jihad

In [3]:
# df.head() ekhane amra chaile koita row dekhte chai taw define kore dite pari.
df.head(10)

   col1  col2   col3
0     8   375    jon
1     1   343  safia
2     1   287  jihad
3     9   463  jihad
4     4   495  jihad
5     6   188    jon
6     3   105  jihad
7     5   236  steve
8     3   234    jon
9     7   251  jihad

In [4]:
# df.tail()  it returns the last 5 rows of the dataframe
df.tail()

   col1  col2   col3
5     6   188    jon
6     3   105  jihad
7     5   236  steve
8     3   234    jon
9     7   251  jihad

### 2. shape() method

In [5]:
# df.shape  it returns the number of rows and columns in the dataframe
df.shape

(10, 3)

### 3. info() method

In [6]:
df.info()  # it returns the information about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    10 non-null     int64
 1   col2    10 non-null     int64
 2   col3    10 non-null     str
dtypes: int64(2), str(1)
memory usage: 372.0 bytes

### 4. describe() method

In [7]:
df.describe() # it returns the statistical summary of the dataframe

            col1        col2
count  10.000000   10.000000
mean    4.700000  297.700000
std     2.790858  121.840561
min     1.000000  105.000000
25%     3.000000  234.500000
50%     4.500000  269.000000
75%     6.750000  367.000000
max     9.000000  495.000000

In [8]:
df.describe(include='str')

         col3
count      10
unique      4
top     jihad
freq        5

### function for see all the necessery things

In [9]:
def inspect(df):
    print(f"Shape: {df.shape}")
    display(df.head())
    display(df.describe())
    display(df.isnull().sum())

inspect(df)

Shape: (10, 3)

   col1  col2   col3
0     8   375    jon
1     1   343  safia
2     1   287  jihad
3     9   463  jihad
4     4   495  jihad

            col1        col2
count  10.000000   10.000000
mean    4.700000  297.700000
std     2.790858  121.840561
min     1.000000  105.000000
25%     3.000000  234.500000
50%     4.500000  269.000000
75%     6.750000  367.000000
max     9.000000  495.000000

col1    0
col2    0
col3    0
dtype: int64

## unique() and sort() method

### unique()

In [10]:
# df.unique()  it returns the unique values in the dataframe
df['col3'].unique()

<StringArray>
['jon', 'safia', 'jihad', 'steve']
Length: 4, dtype: str

In [11]:
# kotogula unique value ase sheta dekhete nunique() method use kora hoy
df['col3'].nunique()

4

In [12]:
# kon unique value kotobar use kora hoise eta dekhte value_counts() method use kora hoy
df['col3'].value_counts()

col3
jihad    5
jon      3
safia    1
steve    1
Name: count, dtype: int64

### sort_values()

In [13]:
# ami chai kono column er value ke sorted dekhte. sort_values() method use kora hoy ejonne.
df.sort_values(by='col2', ascending=False)  # it returns the dataframe sorted by col2 in descending order

   col1  col2   col3
4     4   495  jihad
3     9   463  jihad
0     8   375    jon
1     1   343  safia
2     1   287  jihad
9     7   251  jihad
7     5   236  steve
8     3   234    jon
5     6   188    jon
6     3   105  jihad

## apply() and map() method - vvi

In [14]:
df2 = pd.DataFrame({
    "Name": ["Jihad", "Rahim", "Karim", "Safia"],
    "Marks": [80, 65, 90, 75],
    "Age": [23, 22, 24, 21]
})

df2

    Name  Marks  Age
0  Jihad     80   23
1  Rahim     65   22
2  Karim     90   24
3  Safia     75   21

### apply() method

In [15]:
# etokhon to in build method apply korlam. ami chaile amar nijer customized method o apply korte pari. and etar method holo apply() method.
# apply() method এর argument হিসেবে যেকোনো function pass করা যায়।
# Function CALL করা যাবে না, শুধু function এর নাম pass করতে হবে।

# apply() syntax: df['column_name'].apply(function_name)


def add_five(x):
    return x + 5

df2["Marks"].apply(add_five)

0    85
1    70
2    95
3    80
Name: Marks, dtype: int64

In [16]:
# আরেকটি custom function

def make_upper(text):
    return text.upper()

df2["Name"].apply(make_upper)

0    JIHAD
1    RAHIM
2    KARIM
3    SAFIA
Name: Name, dtype: str

In [17]:
# Python এর built-in function ও apply() এর argument হিসেবে ব্যবহার করা যায়।

# len() প্রতিটি string এর length বের করে।

df2["Name"].apply(len)

0    5
1    5
2    5
3    5
Name: Name, dtype: int64

In [18]:
# apply method full dataset er uporew kaj korte pare jemon:

# প্রতিটি column এর maximum value বের করবে
df2.apply(max) # max() kintu ekta method. but apply() er moddhe call kora jabe na. just pass korlam.

Name     Safia
Marks       90
Age         24
dtype: object

### map() method

In [19]:
# map() একটি column(series)-এর প্রতিটি value-এর ওপর একই function চালায় এবং একটি নতুন Series return করে।

# apply() and map() duitai same function duitari syntax same. just apply() is more powerful chaile full dataset er upor apply kora jabe, chaile single column er upor apply kora jabe. but map() is only for single column.

# map() syntax: df['column_name'].map(function_name)

In [20]:
# নিজের (custom) function ব্যবহার

def add_five(x):
    return x + 5

df2["Marks"].map(add_five)

0    85
1    70
2    95
3    80
Name: Marks, dtype: int64

In [21]:
# আরেকটি custom function

def make_upper(text):
    return text.upper()

df2["Name"].map(make_upper)

0    JIHAD
1    RAHIM
2    KARIM
3    SAFIA
Name: Name, dtype: str

In [22]:
# Python এর built-in function ব্যবহার

df2["Name"].map(len)

0    5
1    5
2    5
3    5
Name: Name, dtype: int64

### lambda function in both map() and apply() method

In [23]:
# lambda হলো Python-এর একটি anonymous (নামবিহীন) function।
# ছোট ও এক লাইনের logic লেখার জন্য lambda ব্যবহার করা হয়।
# lambda ব্যবহার করা বাধ্যতামূলক নয়। চাইলে একই কাজ def দিয়ে function লিখেও করা যায়।

# but lambda use korle code ta choto and precise hoy. alada kore r def function likha lage na.

In [24]:
# lambda function in apply() method

df2["Marks"].apply(lambda x: x + 5)

df2["Marks"].apply(lambda x: x * 2)

df2["Name"].apply(lambda x: x + " Student")

df2["Name"].apply(lambda x: x.upper())

pass

In [25]:
# lambda function in map() method

df2["Marks"].map(lambda x: x + 5)

df2["Marks"].map(lambda x: x * 2)

df2["Name"].map(lambda x: x + " Student")

df2["Name"].map(lambda x: x.upper())

pass

## save and load dataset

In [26]:
# 1. Save CSV WITHOUT the index column
df.to_csv("my_data.csv", index=False)

# Read the CSV normally
pd.read_csv("my_data.csv")

   col1  col2   col3
0     8   375    jon
1     1   343  safia
2     1   287  jihad
3     9   463  jihad
4     4   495  jihad
5     6   188    jon
6     3   105  jihad
7     5   236  steve
8     3   234    jon
9     7   251  jihad

In [27]:
# 2. Save CSV WITH the index column (default behavior)
df.to_csv("my_data_with_index.csv")

# Read the CSV with index column. ekhane extra unnamed column show korse.
pd.read_csv("my_data_with_index.csv")

   Unnamed: 0  col1  col2   col3
0           0     8   375    jon
1           1     1   343  safia
2           2     1   287  jihad
3           3     9   463  jihad
4           4     4   495  jihad
5           5     6   188    jon
6           6     3   105  jihad
7           7     5   236  steve
8           8     3   234    jon
9           9     7   251  jihad

In [28]:
# extra unnamed column dekhte na chaile evabe load korbo
pd.read_csv("my_data_with_index.csv", index_col=0)

   col1  col2   col3
0     8   375    jon
1     1   343  safia
2     1   287  jihad
3     9   463  jihad
4     4   495  jihad
5     6   188    jon
6     3   105  jihad
7     5   236  steve
8     3   234    jon
9     7   251  jihad

## sort method - sort_values()

In [29]:
import pandas as pd

# Sample Dataset
df = pd.DataFrame({
    "Department": ["CSE", "EEE", "CSE", "BBA", "EEE", "BBA", "CSE", "EEE"],
    "Student": ["Rahim", "Mina", "Karim", "Hasan", "Nabil", "Sadia", "Sakib", "Rita"],
    "Marks": [85, 92, 92, 78, 85, 95, 78, 92],
    "Attendance": [90, 88, 95, 80, 91, 97, 85, 89]
})

df

  Department Student  Marks  Attendance
0        CSE   Rahim     85          90
1        EEE    Mina     92          88
2        CSE   Karim     92          95
3        BBA   Hasan     78          80
4        EEE   Nabil     85          91
5        BBA   Sadia     95          97
6        CSE   Sakib     78          85
7        EEE    Rita     92          89

### 1. Single Column Sort

In [30]:
# Marks অনুযায়ী ছোট থেকে বড় (Ascending)
df.sort_values(by="Marks")

  Department Student  Marks  Attendance
3        BBA   Hasan     78          80
6        CSE   Sakib     78          85
4        EEE   Nabil     85          91
0        CSE   Rahim     85          90
2        CSE   Karim     92          95
1        EEE    Mina     92          88
7        EEE    Rita     92          89
5        BBA   Sadia     95          97

In [31]:
# Marks অনুযায়ী বড় থেকে ছোট (Descending)
df.sort_values(by="Marks", ascending=False)

  Department Student  Marks  Attendance
5        BBA   Sadia     95          97
1        EEE    Mina     92          88
7        EEE    Rita     92          89
2        CSE   Karim     92          95
4        EEE   Nabil     85          91
0        CSE   Rahim     85          90
3        BBA   Hasan     78          80
6        CSE   Sakib     78          85

In [32]:
# Student নাম Alphabetically সাজানো
df.sort_values(by="Student")

  Department Student  Marks  Attendance
3        BBA   Hasan     78          80
2        CSE   Karim     92          95
1        EEE    Mina     92          88
4        EEE   Nabil     85          91
0        CSE   Rahim     85          90
7        EEE    Rita     92          89
5        BBA   Sadia     95          97
6        CSE   Sakib     78          85

### 2. Multiple Column Sort

In [33]:
# প্রথমে Marks অনুযায়ী বড় থেকে ছোট।
# যদি Marks সমান হয়, তাহলে Attendance অনুযায়ী ছোট থেকে বড়।
df.sort_values(
    by=["Marks", "Attendance"],
    ascending=[False, True]
)

  Department Student  Marks  Attendance
5        BBA   Sadia     95          97
1        EEE    Mina     92          88
7        EEE    Rita     92          89
2        CSE   Karim     92          95
0        CSE   Rahim     85          90
4        EEE   Nabil     85          91
3        BBA   Hasan     78          80
6        CSE   Sakib     78          85

In [34]:
# প্রথমে Department অনুযায়ী Alphabetically।
# একই Department হলে Marks অনুযায়ী বড় থেকে ছোট।
df.sort_values(
    by=["Department", "Marks"],
    ascending=[True, False]
)

  Department Student  Marks  Attendance
5        BBA   Sadia     95          97
3        BBA   Hasan     78          80
2        CSE   Karim     92          95
0        CSE   Rahim     85          90
6        CSE   Sakib     78          85
1        EEE    Mina     92          88
7        EEE    Rita     92          89
4        EEE   Nabil     85          91

In [ ]:
# প্রথমে Marks অনুযায়ী ছোট থেকে বড়।
# Marks সমান হলে Student নাম অনুযায়ী Alphabetically।
df.sort_values(
    by=["Marks", "Student"],
    ascending=[True, True]
)

  Department Student  Marks  Attendance
3        BBA   Hasan     78          80
6        CSE   Sakib     78          85
4        EEE   Nabil     85          91
0        CSE   Rahim     85          90
2        CSE   Karim     92          95
1        EEE    Mina     92          88
7        EEE    Rita     92          89
5        BBA   Sadia     95          97