In [29]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'col1': np.random.randint(1,10, size=10),
    'col2': np.random.randint(100,500, size=10),
    'col3': np.random.choice(['steve', 'jon', 'safia', 'jihad'], size=10)
})

df

   col1  col2   col3
0     9   289  steve
1     1   385  safia
2     6   258  safia
3     2   319    jon
4     7   121  steve
5     8   174  jihad
6     6   171  steve
7     5   100  safia
8     8   290  safia
9     4   114  safia

## 4 mathods that always have to use of any dataset to get info

### 1. head() and tail() method

In [2]:
# df.head()  it returns the first 5 rows of the dataframe
df.head()

   col1  col2   col3
0     1   332    jon
1     4   354    jon
2     6   177    jon
3     1   328  jihad
4     6   210  steve

In [3]:
# df.head() ekhane amra chaile koita row dekhte chai taw define kore dite pari.
df.head(10)

   col1  col2   col3
0     1   332    jon
1     4   354    jon
2     6   177    jon
3     1   328  jihad
4     6   210  steve
5     4   432  steve
6     2   315  safia
7     3   404  safia
8     3   380  jihad
9     9   375  steve

In [4]:
# df.tail()  it returns the last 5 rows of the dataframe
df.tail()

   col1  col2   col3
5     4   432  steve
6     2   315  safia
7     3   404  safia
8     3   380  jihad
9     9   375  steve

### 2. shape() method

In [5]:
# df.shape  it returns the number of rows and columns in the dataframe
df.shape

(10, 3)

### 3. info() method

In [6]:
df.info()  # it returns the information about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    10 non-null     int64
 1   col2    10 non-null     int64
 2   col3    10 non-null     str
dtypes: int64(2), str(1)
memory usage: 372.0 bytes

### 4. describe() method

In [7]:
df.describe() # it returns the statistical summary of the dataframe

            col1        col2
count  10.000000   10.000000
mean    3.900000  330.700000
std     2.514403   80.978804
min     1.000000  177.000000
25%     2.250000  318.250000
50%     3.500000  343.000000
75%     5.500000  378.750000
max     9.000000  432.000000

In [8]:
df.describe(include='str')

       col3
count    10
unique    4
top     jon
freq      3

### function for see all the necessery things

In [9]:
def inspect(df):
    print(f"Shape: {df.shape}")
    display(df.head())
    display(df.describe())
    display(df.isnull().sum())

inspect(df)

Shape: (10, 3)

   col1  col2   col3
0     1   332    jon
1     4   354    jon
2     6   177    jon
3     1   328  jihad
4     6   210  steve

            col1        col2
count  10.000000   10.000000
mean    3.900000  330.700000
std     2.514403   80.978804
min     1.000000  177.000000
25%     2.250000  318.250000
50%     3.500000  343.000000
75%     5.500000  378.750000
max     9.000000  432.000000

col1    0
col2    0
col3    0
dtype: int64

## unique() and sort() method

### unique()

In [10]:
# df.unique()  it returns the unique values in the dataframe
df['col3'].unique()

<StringArray>
['jon', 'jihad', 'steve', 'safia']
Length: 4, dtype: str

In [11]:
# kotogula unique value ase sheta dekhete nunique() method use kora hoy
df['col3'].nunique()

4

In [12]:
# kon unique value kotobar use kora hoise eta dekhte value_counts() method use kora hoy
df['col3'].value_counts()

col3
jon      3
steve    3
jihad    2
safia    2
Name: count, dtype: int64

### sort_values()

In [13]:
# ami chai kono column er value ke sorted dekhte. sort_values() method use kora hoy ejonne.
df.sort_values(by='col2', ascending=False)  # it returns the dataframe sorted by col2 in descending order

   col1  col2   col3
5     4   432  steve
7     3   404  safia
8     3   380  jihad
9     9   375  steve
1     4   354    jon
0     1   332    jon
3     1   328  jihad
6     2   315  safia
4     6   210  steve
2     6   177    jon

## apply() and map() method - vvi

In [14]:
df2 = pd.DataFrame({
    "Name": ["Jihad", "Rahim", "Karim", "Safia"],
    "Marks": [80, 65, 90, 75],
    "Age": [23, 22, 24, 21]
})

df2

    Name  Marks  Age
0  Jihad     80   23
1  Rahim     65   22
2  Karim     90   24
3  Safia     75   21

### apply() method

In [15]:
# etokhon to in build method apply korlam. ami chaile amar nijer customized method o apply korte pari. and etar method holo apply() method.
# apply() method এর argument হিসেবে যেকোনো function pass করা যায়।
# Function CALL করা যাবে না, শুধু function এর নাম pass করতে হবে।

# apply() syntax: df['column_name'].apply(function_name)


def add_five(x):
    return x + 5

df2["Marks"].apply(add_five)

0    85
1    70
2    95
3    80
Name: Marks, dtype: int64

In [16]:
# আরেকটি custom function

def make_upper(text):
    return text.upper()

df2["Name"].apply(make_upper)

0    JIHAD
1    RAHIM
2    KARIM
3    SAFIA
Name: Name, dtype: str

In [17]:
# Python এর built-in function ও apply() এর argument হিসেবে ব্যবহার করা যায়।

# len() প্রতিটি string এর length বের করে।

df2["Name"].apply(len)

0    5
1    5
2    5
3    5
Name: Name, dtype: int64

In [18]:
# apply method full dataset er uporew kaj korte pare jemon:

# প্রতিটি column এর maximum value বের করবে
df2.apply(max) # max() kintu ekta method. but apply() er moddhe call kora jabe na. just pass korlam.

Name     Safia
Marks       90
Age         24
dtype: object

### map() method

In [19]:
# map() একটি column(series)-এর প্রতিটি value-এর ওপর একই function চালায় এবং একটি নতুন Series return করে।

# apply() and map() duitai same function duitari syntax same. just apply() is more powerful chaile full dataset er upor apply kora jabe, chaile single column er upor apply kora jabe. but map() is only for single column.

# map() syntax: df['column_name'].map(function_name)

In [20]:
# নিজের (custom) function ব্যবহার

def add_five(x):
    return x + 5

df2["Marks"].map(add_five)

0    85
1    70
2    95
3    80
Name: Marks, dtype: int64

In [21]:
# আরেকটি custom function

def make_upper(text):
    return text.upper()

df2["Name"].map(make_upper)

0    JIHAD
1    RAHIM
2    KARIM
3    SAFIA
Name: Name, dtype: str

In [22]:
# Python এর built-in function ব্যবহার

df2["Name"].map(len)

0    5
1    5
2    5
3    5
Name: Name, dtype: int64

### lambda function in both map() and apply() method

In [23]:
# lambda হলো Python-এর একটি anonymous (নামবিহীন) function।
# ছোট ও এক লাইনের logic লেখার জন্য lambda ব্যবহার করা হয়।
# lambda ব্যবহার করা বাধ্যতামূলক নয়। চাইলে একই কাজ def দিয়ে function লিখেও করা যায়।

# but lambda use korle code ta choto and precise hoy. alada kore r def function likha lage na.

In [24]:
# lambda function in apply() method

df2["Marks"].apply(lambda x: x + 5)

df2["Marks"].apply(lambda x: x * 2)

df2["Name"].apply(lambda x: x + " Student")

df2["Name"].apply(lambda x: x.upper())

pass

In [25]:
# lambda function in map() method

df2["Marks"].map(lambda x: x + 5)

df2["Marks"].map(lambda x: x * 2)

df2["Name"].map(lambda x: x + " Student")

df2["Name"].map(lambda x: x.upper())

pass

## save and load dataset

In [26]:
# 1. Save CSV WITHOUT the index column
df.to_csv("my_data.csv", index=False)

# Read the CSV normally
pd.read_csv("my_data.csv")

   col1  col2   col3
0     1   332    jon
1     4   354    jon
2     6   177    jon
3     1   328  jihad
4     6   210  steve
5     4   432  steve
6     2   315  safia
7     3   404  safia
8     3   380  jihad
9     9   375  steve

In [27]:
# 2. Save CSV WITH the index column (default behavior)
df.to_csv("my_data_with_index.csv")

# Read the CSV with index column. ekhane extra unnamed column show korse.
pd.read_csv("my_data_with_index.csv")

   Unnamed: 0  col1  col2   col3
0           0     1   332    jon
1           1     4   354    jon
2           2     6   177    jon
3           3     1   328  jihad
4           4     6   210  steve
5           5     4   432  steve
6           6     2   315  safia
7           7     3   404  safia
8           8     3   380  jihad
9           9     9   375  steve

In [28]:
# extra unnamed column dekhte na chaile evabe load korbo
pd.read_csv("my_data_with_index.csv", index_col=0)

   col1  col2   col3
0     1   332    jon
1     4   354    jon
2     6   177    jon
3     1   328  jihad
4     6   210  steve
5     4   432  steve
6     2   315  safia
7     3   404  safia
8     3   380  jihad
9     9   375  steve