In [72]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'col1': np.random.randint(1,10, size=10),
    'col2': np.random.randint(100,500, size=10),
    'col3': np.random.choice(['steve', 'jon', 'safia', 'jihad'], size=10)
})

df

   col1  col2   col3
0     3   289  safia
1     3   130  steve
2     7   221  safia
3     9   333  steve
4     8   413  steve
5     1   244  jihad
6     9   388  safia
7     8   390  jihad
8     8   381  safia
9     4   213  jihad

## 4 mathods that always have to use of any dataset to get info

### 1. head() and tail() method

In [73]:
# df.head()  it returns the first 5 rows of the dataframe
df.head()

   col1  col2   col3
0     3   289  safia
1     3   130  steve
2     7   221  safia
3     9   333  steve
4     8   413  steve

In [74]:
# df.head() ekhane amra chaile koita row dekhte chai taw define kore dite pari.
df.head(10)

   col1  col2   col3
0     3   289  safia
1     3   130  steve
2     7   221  safia
3     9   333  steve
4     8   413  steve
5     1   244  jihad
6     9   388  safia
7     8   390  jihad
8     8   381  safia
9     4   213  jihad

In [75]:
# df.tail()  it returns the last 5 rows of the dataframe
df.tail()

   col1  col2   col3
5     1   244  jihad
6     9   388  safia
7     8   390  jihad
8     8   381  safia
9     4   213  jihad

### 2. shape() method

In [76]:
# df.shape  it returns the number of rows and columns in the dataframe
df.shape

(10, 3)

### 3. info() method

In [77]:
df.info()  # it returns the information about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    10 non-null     int64
 1   col2    10 non-null     int64
 2   col3    10 non-null     str
dtypes: int64(2), str(1)
memory usage: 372.0 bytes

### 4. describe() method

In [78]:
df.describe() # it returns the statistical summary of the dataframe

           col1       col2
count  10.00000   10.00000
mean    6.00000  300.20000
std     2.94392   95.58568
min     1.00000  130.00000
25%     3.25000  226.75000
50%     7.50000  311.00000
75%     8.00000  386.25000
max     9.00000  413.00000

In [79]:
df.describe(include='str')

         col3
count      10
unique      3
top     safia
freq        4

## unique() and sort() method

### unique()

In [80]:
# df.unique()  it returns the unique values in the dataframe
df['col3'].unique()

<StringArray>
['safia', 'steve', 'jihad']
Length: 3, dtype: str

In [81]:
# kotogula unique value ase sheta dekhete nunique() method use kora hoy
df['col3'].nunique()

3

In [82]:
# kon unique value kotobar use kora hoise eta dekhte value_counts() method use kora hoy
df['col3'].value_counts()

col3
safia    4
steve    3
jihad    3
Name: count, dtype: int64

### sort_values()

In [83]:
# ami chai kono column er value ke sorted dekhte. sort_values() method use kora hoy ejonne.
df.sort_values(by='col2', ascending=False)  # it returns the dataframe sorted by col2 in descending order

   col1  col2   col3
4     8   413  steve
7     8   390  jihad
6     9   388  safia
8     8   381  safia
3     9   333  steve
0     3   289  safia
5     1   244  jihad
2     7   221  safia
9     4   213  jihad
1     3   130  steve

## apply() and map() method

### apply() method - vvi

In [84]:
# apply() method full dataset er upor customized function apply korte use kora hoy. and map() method specific column er upor customized function apply korte use kora hoy.

# map() diye ja ja kora jay tar shobgulai apply() diyei kora jay. but single column niye kaj korle convention holo map niye kaj kora but syntax mone na thakle obviously apply() use kora jabe.

In [85]:
# etokhon to in build method apply korlam. ami chaile amar nijer customized method o apply korte pari. and etar method holo apply() method.

# apply() method e ami jekono function ke argument hishebe pass korte pari. note: function call kora jabe na.

def my_func(x):
    return x*2

df['col3'].apply(my_func)

0    safiasafia
1    stevesteve
2    safiasafia
3    stevesteve
4    stevesteve
5    jihadjihad
6    safiasafia
7    jihadjihad
8    safiasafia
9    jihadjihad
Name: col3, dtype: str

In [86]:
# not only amar customized function, ami chaile python er built in function ow apply() method er argument hishebe pass korte pari.

# len()  holo python er built in function.  string er length ber kore dey.

df['col3'].apply(len)

0    5
1    5
2    5
3    5
4    5
5    5
6    5
7    5
8    5
9    5
Name: col3, dtype: int64

### map() method

In [87]:
# map() একটি column(series)-এর প্রতিটি value-এর ওপর একই function চালায় এবং একটি নতুন Series return করে।

In [88]:
df = pd.DataFrame({
    "Name": ["Jihad", "Rahim", "Karim", "Safia"],
    "Marks": [80, 65, 90, 75]
})

df

    Name  Marks
0  Jihad     80
1  Rahim     65
2  Karim     90
3  Safia     75

In [89]:
# ami marks column er protita value er sathe 5 add korbo

# ekhane lambda holo ekta function. python e function define korte jemon def keyword use kora hoy, tomoni map e lambda keyword or function ta use kora hoy.

# column e arithmatic operation apply korte lambda actually use kora hoy na. karon arithmatic operation aaro easy way tei apply kora jay. eta just example hishebe dekhano. map e amra ekta column er jeokno datatype er value er upor operation chalaite pari. tai map use kora hoy actually. 

df["Marks"].map(lambda x: x + 5)

0    85
1    70
2    95
3    80
Name: Marks, dtype: int64

In [90]:
df["Marks"].map(lambda x: x * 2)

0    160
1    130
2    180
3    150
Name: Marks, dtype: int64

In [91]:
df["Name"].map(
    lambda x: x + " Student"
)

0    Jihad Student
1    Rahim Student
2    Karim Student
3    Safia Student
Name: Name, dtype: str

In [92]:
df["Name"].map(
    lambda x: x.upper()
)

0    JIHAD
1    RAHIM
2    KARIM
3    SAFIA
Name: Name, dtype: str

## save and load dataset

In [93]:
# 1. Save CSV WITHOUT the index column
df.to_csv("my_data.csv", index=False)

# Read the CSV normally
pd.read_csv("my_data.csv")

    Name  Marks
0  Jihad     80
1  Rahim     65
2  Karim     90
3  Safia     75

In [94]:
# 2. Save CSV WITH the index column (default behavior)
df.to_csv("my_data_with_index.csv")

# Read the CSV with index column. ekhane extra unnamed column show korse.
pd.read_csv("my_data_with_index.csv")

   Unnamed: 0   Name  Marks
0           0  Jihad     80
1           1  Rahim     65
2           2  Karim     90
3           3  Safia     75

In [95]:
# extra unnamed column dekhte na chaile evabe load korbo
pd.read_csv("my_data_with_index.csv", index_col=0)

    Name  Marks
0  Jihad     80
1  Rahim     65
2  Karim     90
3  Safia     75