In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'col1': np.random.randint(1,10, size=10),
    'col2': np.random.randint(100,500, size=10),
    'col3': np.random.choice(['steve', 'jon', 'safia', 'jihad'], size=10)
})

df

   col1  col2   col3
0     7   378  jihad
1     3   111  safia
2     1   286  safia
3     6   387    jon
4     4   210  steve
5     2   129  steve
6     8   466  steve
7     9   351    jon
8     6   477    jon
9     2   252  steve

## 3 mathod that always have to use of any dataset to get info

### 1. head() and tail() method

In [2]:
# df.head()  it returns the first 5 rows of the dataframe
df.head()

   col1  col2   col3
0     7   378  jihad
1     3   111  safia
2     1   286  safia
3     6   387    jon
4     4   210  steve

In [3]:
# df.head() ekhane amra chaile koita row dekhte chai taw define kore dite pari.
df.head(10)

   col1  col2   col3
0     7   378  jihad
1     3   111  safia
2     1   286  safia
3     6   387    jon
4     4   210  steve
5     2   129  steve
6     8   466  steve
7     9   351    jon
8     6   477    jon
9     2   252  steve

In [4]:
# df.tail()  it returns the last 5 rows of the dataframe
df.tail()

   col1  col2   col3
5     2   129  steve
6     8   466  steve
7     9   351    jon
8     6   477    jon
9     2   252  steve

### 2. shape() method

In [5]:
# df.shape  it returns the number of rows and columns in the dataframe
df.shape

(10, 3)

### 3. info() method

In [6]:
df.info()  # it returns the information about the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    10 non-null     int64
 1   col2    10 non-null     int64
 2   col3    10 non-null     str
dtypes: int64(2), str(1)
memory usage: 372.0 bytes

## unique() and sort() method

### unique()

In [7]:
# df.unique()  it returns the unique values in the dataframe
df['col3'].unique()

<StringArray>
['jihad', 'safia', 'jon', 'steve']
Length: 4, dtype: str

In [8]:
# kotogula unique value ase sheta dekhete nunique() method use kora hoy
df['col3'].nunique()

4

In [ ]:
# kon unique value kotobar use kora hoise eta dekhte value_counts() method use kora hoy
df['col3'].value_counts()

col3
steve    4
jon      3
safia    2
jihad    1
Name: count, dtype: int64

### sort_values()

In [12]:
# ami chai kono column er value ke sorted dekhte. sort_values() method use kora hoy ejonne.
df.sort_values(by='col2', ascending=False)  # it returns the dataframe sorted by col2 in descending order

   col1  col2   col3
8     6   477    jon
6     8   466  steve
3     6   387    jon
0     7   378  jihad
7     9   351    jon
2     1   286  safia
9     2   252  steve
4     4   210  steve
5     2   129  steve
1     3   111  safia

## apply() method - vvi

In [13]:
# etokhon to in build method apply korlam. ami chaile amar nijer customized method o apply korte pari. and etar method holo apply() method.

# apply() method e ami jekono function ke argument hishebe pass korte pari. note: function call kora jabe na.

def my_func(x):
    return x*2

df['col3'].apply(my_func)

0    jihadjihad
1    safiasafia
2    safiasafia
3        jonjon
4    stevesteve
5    stevesteve
6    stevesteve
7        jonjon
8        jonjon
9    stevesteve
Name: col3, dtype: str

In [14]:
# not only amar customized function, ami chaile python er built in function ow apply() method er argument hishebe pass korte pari.

# len()  holo python er built in function.  string er length ber kore dey.

df['col3'].apply(len)

0    5
1    5
2    5
3    3
4    5
5    5
6    5
7    3
8    3
9    5
Name: col3, dtype: int64

## save and load dataset

In [26]:
# 1. Save CSV WITHOUT the index column
df.to_csv("my_data.csv", index=False)

# Read the CSV normally
pd.read_csv("my_data.csv")

   col1  col2   col3
0     7   378  jihad
1     3   111  safia
2     1   286  safia
3     6   387    jon
4     4   210  steve
5     2   129  steve
6     8   466  steve
7     9   351    jon
8     6   477    jon
9     2   252  steve

In [29]:
# 2. Save CSV WITH the index column (default behavior)
df.to_csv("my_data_with_index.csv")

# Read the CSV with index column. ekhane extra unnamed column show korse.
pd.read_csv("my_data_with_index.csv")

   Unnamed: 0  col1  col2   col3
0           0     7   378  jihad
1           1     3   111  safia
2           2     1   286  safia
3           3     6   387    jon
4           4     4   210  steve
5           5     2   129  steve
6           6     8   466  steve
7           7     9   351    jon
8           8     6   477    jon
9           9     2   252  steve

In [ ]:
# extra unnamed column dekhte na chaile evabe load korbo
pd.read_csv("my_data_with_index.csv", index_col=0)

   col1  col2   col3
0     7   378  jihad
1     3   111  safia
2     1   286  safia
3     6   387    jon
4     4   210  steve
5     2   129  steve
6     8   466  steve
7     9   351    jon
8     6   477    jon
9     2   252  steve