In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Class": ["10", "10", "10", "9", "9", "9"],
    "Section": ["A", "A", "B", "A", "B", "B"],
    "Student": ["Rahim", "Karim", "Sakib", "Mina", "Rita", "Nabil"],
    "Marks": [80, 90, 70, 85, 75, 95]
})

print(df)

  Class Section Student  Marks
0    10       A   Rahim     80
1    10       A   Karim     90
2    10       B   Sakib     70
3     9       A    Mina     85
4     9       B    Rita     75
5     9       B   Nabil     95

In [3]:
df.groupby("Class")

In [4]:
# upore ekta column diye group kora hosie. but dekhtei paccho table ta dekha jay na. amake dataframe er ekta object pathay.

# table ta dekhte hole amake kichu aggregation function use korle ekta visual table pabo.

# শুধু Class দিয়ে গ্রুপ, তারপর Marks এর যোগফল
df.groupby('Class')['Marks'].sum()

Class
10    240
9     255
Name: Marks, dtype: int64

In [5]:
df.groupby('Section')['Marks'].sum()

Section
A    255
B    240
Name: Marks, dtype: int64

In [6]:
# Class ও Section দিয়ে গ্রুপ
df.groupby(['Class', 'Section'])['Marks'].sum()

Class  Section
10     A          170
       B           70
9      A           85
       B          170
Name: Marks, dtype: int64

In [7]:
# agg() দিয়ে count, sum, mean
df.groupby(['Class', 'Section'])['Marks'].agg(['count', 'sum', 'mean'])

               count  sum  mean
Class Section
10    A            2  170  85.0
      B            1   70  70.0
9     A            1   85  85.0
      B            2  170  85.0

In [8]:
# section wise maximum marks student ber korbo.
max_id_by_section = df.groupby(['Section'])['Marks'].idxmax()
df.loc[max_id_by_section][['Section', 'Student', 'Marks']]

  Section Student  Marks
1       A   Karim     90
5       B   Nabil     95

In [9]:
# প্রতিটি গ্রুপের সর্বোচ্চ Marks-এর সারি বের করা
max_id_by_group = df.groupby(['Class', 'Section'])['Marks'].idxmax()
df.loc[max_id_by_group]

  Class Section Student  Marks
1    10       A   Karim     90
2    10       B   Sakib     70
3     9       A    Mina     85
5     9       B   Nabil     95